#!/bin/bash
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL

CREATE USER ${CKAN_USER} PASSWORD '${CKAN_PASSWORD}';

CREATE DATABASE ${CKAN_USER} WITH OWNER ${CKAN_USER};

EOSQL