#!/bin/bash
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL

CREATE USER ${CKAN_POSTGRESQL_USER} PASSWORD '${CKAN_POSTGRESQL_PASSWORD}';
CREATE USER ${CKAN_POSTGRESQL_DATASTORE_USER} PASSWORD '${CKAN_POSTGRESQL_DATASTORE_PASSWORD}';

CREATE DATABASE ${CKAN_POSTGRESQL_DB} WITH OWNER ${CKAN_POSTGRESQL_USER};
CREATE DATABASE ${CKAN_POSTGRESQL_DATASTORE_DB} WITH OWNER ${CKAN_POSTGRESQL_USER};

EOSQL