/**
 * Python script to fetch the MOBILITY_THEME_TREE values:
 *
 * g = rdflib.Graph()
 * g.parse('https://mobilitydcat-ap.github.io/controlled-vocabularies/mobility-theme/latest/mobility-theme.ttl')
 * for top_concept in g.subjects(rdflib.namespace.SKOS.broader, rdflib.URIRef('https://w3id.org/mobilitydcat-ap/mobility-theme/data-content-category')):
 *     sub_concepts = [sub_concept for sub_concept in g.subjects(rdflib.namespace.SKOS.broader, top_concept)]
 *     print(f'"{top_concept}": [')
 *     for cub_concept in sub_concepts:
 *         print(f'"{cub_concept}",')
 *     print('],')
 */
export const MOBILITY_THEME_TREE = {
  "https://w3id.org/mobilitydcat-ap/mobility-theme/air-and-space-travel": [
  ],
  "https://w3id.org/mobilitydcat-ap/mobility-theme/cycle-network-data": [
    "https://w3id.org/mobilitydcat-ap/mobility-theme/network-closures-diversions",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/network-detailed-attributes",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/network-geometry-and-lane-character",
  ],
  "https://w3id.org/mobilitydcat-ap/mobility-theme/dynamic-traffic-signs-and-regulations": [
    "https://w3id.org/mobilitydcat-ap/mobility-theme/bridge-closures-and-access-conditions",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/direction-of-travel-on-reversible-lanes",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/dynamic-overtaking-bans-on-heavy-goods-vehicles",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/dynamic-speed-limits",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/lane-closures-and-access-conditions",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/other-access-restrictions-and-traffic-regulations",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/other-temporary-traffic-management-measures-or-plans",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/road-closures-and-access-conditions",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/tunnel-closures-and-access-conditions",
  ],
  "https://w3id.org/mobilitydcat-ap/mobility-theme/filling-and-charging-stations": [
    "https://w3id.org/mobilitydcat-ap/mobility-theme/availability-of-charging-points-for-electric-vehicles",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/availability-of-filling-stations",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/location-and-conditions-of-charging-points",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/location-and-conditions-of-filling-stations",
  ],
  "https://w3id.org/mobilitydcat-ap/mobility-theme/freight-and-logistics": [
    "https://w3id.org/mobilitydcat-ap/mobility-theme/availability-of-delivery-areas",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/freight-delivery-regulations",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/location-of-delivery-areas",
  ],
  "https://w3id.org/mobilitydcat-ap/mobility-theme/general-information-for-trip-planning-": [
    "https://w3id.org/mobilitydcat-ap/mobility-theme/address-identifiers",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/parameters-needed-to-calculate-costs",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/parameters-needed-to-calculate-environmental-factors",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/points-of-interest",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/topographic-places",
  ],
  "https://w3id.org/mobilitydcat-ap/mobility-theme/other": [
  ],
  "https://w3id.org/mobilitydcat-ap/mobility-theme/parking-service-and-rest-area-information": [
    "https://w3id.org/mobilitydcat-ap/mobility-theme/bike-parking-locations",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/car-parking-availability",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/car-parking-locations-and-conditions",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/park-and-ride-stops",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/service-and-rest-area-availability",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/service-and-rest-area-locations-and-conditions",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/truck-parking-availability",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/truck-parking-locations-and-conditions",
  ],
  "https://w3id.org/mobilitydcat-ap/mobility-theme/pedestrian-network-data": [
    "https://w3id.org/mobilitydcat-ap/mobility-theme/pedestrian-accessibility-facilities",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/pedestrian-network-geometry",
  ],
  "https://w3id.org/mobilitydcat-ap/mobility-theme/public-transport-non-scheduled-transport": [
    "https://w3id.org/mobilitydcat-ap/mobility-theme/accesibility-information-for-vehicles",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/environmental-standards-for-vehicles",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/fares",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/locations-and-stations",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/provider-data",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/reservation-and-purchase-options",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/service-areas-and-service-times",
  ],
  "https://w3id.org/mobilitydcat-ap/mobility-theme/public-transport-scheduled-transport": [
    "https://w3id.org/mobilitydcat-ap/mobility-theme/basic-commercial-conditions",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/basic-common-standard-fares",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/common-fare-products",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/connection-links",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/disruptions-delays-cancellations",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/environmental-standards-for-vehicles",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/hours-of-operation",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/network-topology-and-routes-lines",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/operational-calendar",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/passenger-classes",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/planned-interchanges-between-scheduled-services",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/purchase-information",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/real-time-estimated-departure-and-arrival-times",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/special-fare-products",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/stop-facilities-accessibility-and-paths-within-facility",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/stop-facilities-geometry-and-map-layout",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/stop-facilities-location-and-features",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/stop-facilities-status-of-features",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/timetables-static",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/transport-operators",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/vehicle-details",
  ],
  "https://w3id.org/mobilitydcat-ap/mobility-theme/real-time-traffic-data": [
    "https://w3id.org/mobilitydcat-ap/mobility-theme/current-travel-times",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/expected-delays",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/location-and-length-of-queues",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/predicted-travel-times",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/speed",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/traffic-data-at-border-crossings-to-third-countries",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/traffic-volume",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/waiting-time-at-border-crossings-to-non-eu-member-states",
  ],
  "https://w3id.org/mobilitydcat-ap/mobility-theme/road-events-and-conditions": [
    "https://w3id.org/mobilitydcat-ap/mobility-theme/accidents-and-incidents",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/poor-road-conditions",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/road-weather-conditions",
  ],
  "https://w3id.org/mobilitydcat-ap/mobility-theme/road-work-information": [
    "https://w3id.org/mobilitydcat-ap/mobility-theme/long-term-road-works",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/short-term-road-works",
  ],
  "https://w3id.org/mobilitydcat-ap/mobility-theme/sharing-and-hiring-services": [
    "https://w3id.org/mobilitydcat-ap/mobility-theme/bike-hiring-availability",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/bike-hiring-stations",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/bike-sharing-availability",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/bike-sharing-locations-and-stations",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/car-hiring-availability",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/car-hiring-stations",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/car-sharing-availability",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/car-sharing-locations-and-stations",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/e-scooter-sharing-availability",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/e-scooter-sharing-locations-and-stations",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/environmental-standards-for-vehicles",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/payment-methods",
  ],
  "https://w3id.org/mobilitydcat-ap/mobility-theme/static-road-network-data": [
    "https://w3id.org/mobilitydcat-ap/mobility-theme/geometry",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/gradients",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/junctions",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/number-of-lanes",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/road-classification",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/road-width",
  ],
  "https://w3id.org/mobilitydcat-ap/mobility-theme/static-traffic-signs-and-regulations": [
    "https://w3id.org/mobilitydcat-ap/mobility-theme/bridge-access-conditions",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/other-static-traffic-signs",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/other-traffic-regulations",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/permanent-access-restrictions",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/speed-limits",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/traffic-circulation-plans",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/tunnel-access-conditions",
  ],
  "https://w3id.org/mobilitydcat-ap/mobility-theme/toll-information": [
    "https://w3id.org/mobilitydcat-ap/mobility-theme/applicable-road-user-charges-and-payment-methods",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/identification-of-tolled-roads",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/location-of-tolling-stations",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/payment-methods-for-tolls",
  ],
  "https://w3id.org/mobilitydcat-ap/mobility-theme/waterways-and-water-bodies": [
  ],
} as const

export type TOP_MOBILITY_THEMES_T = keyof typeof MOBILITY_THEME_TREE
export type SUB_MOBILITY_THEMES_T = (typeof MOBILITY_THEME_TREE)[TOP_MOBILITY_THEMES_T][number]

export const TOP_MOBILITY_THEMES = new Set<TOP_MOBILITY_THEMES_T>(Object.keys(MOBILITY_THEME_TREE) as TOP_MOBILITY_THEMES_T[])
export const SUB_MOBILITY_THEMES = new Set<SUB_MOBILITY_THEMES_T>(Object.values(MOBILITY_THEME_TREE).flat() as SUB_MOBILITY_THEMES_T[])
export const MOBILITY_THEME_LABELS = {
  "https://w3id.org/mobilitydcat-ap/mobility-theme/accesibility-information-for-vehicles": { "en": "Accesibility information for vehicles", "fi": "Ajoneuvojen esteettömyystiedot" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/accidents-and-incidents": { "en": "Accidents and incidents", "fi": "Liikenneonnettomuudet ja -häiriöt" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/address-identifiers": { "en": "Address identifiers", "fi": "Osoitetunnisteet" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/air-and-space-travel": { "en": "Air and space travel", "fi": "Ilma- ja avaruusmatkailu" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/applicable-road-user-charges-and-payment-methods": { "en": "Applicable road user charges and payment methods", "fi": "Sovellettavat tienkäyttömaksut ja maksutavat" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/availability-of-charging-points-for-electric-vehicles": { "en": "Availability of charging points for electric vehicles", "fi": "Sähköajoneuvojen latauspisteiden saatavuus" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/availability-of-delivery-areas": { "en": "Availability of delivery areas", "fi": "Lastaus- ja purkauspaikkojen saatavuus" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/availability-of-filling-stations": { "en": "Availability of filling stations", "fi": "Tankkausasemien saatavuus" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/basic-commercial-conditions": { "en": "Basic commercial conditions", "fi": "Kaupalliset perusehdot" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/basic-common-standard-fares": { "en": "Basic common standard fares", "fi": "Yleiset perusmaksut" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/bike-hiring-availability": { "en": "Bike-hiring Availability", "fi": "Vuokrapyörien saatavuus" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/bike-hiring-stations": { "en": "Bike-hiring Stations", "fi": "Pyöränvuokrausasemat" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/bike-parking-locations": { "en": "Bike-parking locations", "fi": "Polkupyöräparkit" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/bike-sharing-availability": { "en": "Bike sharing Availability", "fi": "Kaupunkipyörien saatavuus" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/bike-sharing-locations-and-stations": { "en": "Bike-sharing Locations and stations", "fi": "Kaupunkipyörien sijainnit ja asemat" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/bridge-access-conditions": { "en": "Bridge access conditions", "fi": "Siltojen käyttörajoitukset" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/bridge-closures-and-access-conditions": { "en": "Bridge closures and access conditions", "fi": "Siltojen sulkemiset ja käyttörajoitukset" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/car-hiring-availability": { "en": "Car-hiring Availability", "fi": "Autonvuokrauksen saatavuus" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/car-hiring-stations": { "en": "Car-hiring Stations", "fi": "Autonvuokrausasemat" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/car-parking-availability": { "en": "Car parking availability", "fi": "Autojen pysäköinnin saatavuus" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/car-parking-locations-and-conditions": { "en": "Car parking locations and conditions", "fi": "Autojen pysäköintipaikat ja -olosuhteet" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/car-sharing-availability": { "en": "Car-sharing Availability", "fi": "Yhteiskäyttöautojen saatavuus" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/car-sharing-locations-and-stations": { "en": "Car-sharing Locations and stations", "fi": "Yhteiskäyttöautojen sijainnit ja asemat" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/common-fare-products": { "en": "Common fare products", "fi": "Yleiset lipputuotteet" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/connection-links": { "en": "Connection links", "fi": "Vaihtoyhteydet ?" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/current-travel-times": { "en": "Current travel times", "fi": "Ajankohtaiset matka-ajat" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/cycle-network-data": { "en": "Cycle network data", "fi": "Pyöräilyverkon tiedot" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/data-content-category": { "en": "Data content category", "fi": "Tietosisällön kategoria" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/data-content-sub-category": { "en": "Data content sub-category", "fi": "Tietosisällön alakategoria" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/direction-of-travel-on-reversible-lanes": { "en": "Direction of travel on reversible lanes", "fi": "Vaihtuvasuuntaisten kaistojen ajosuunta" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/disruptions-delays-cancellations": { "en": "Disruptions, delays, cancellations", "fi": "Häiriöt, viivästykset, peruutukset" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/dynamic-overtaking-bans-on-heavy-goods-vehicles": { "en": "Dynamic overtaking bans on heavy goods vehicles", "fi": "Dynaamiset raskaiden ajoneuvojen ohituskiellot" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/dynamic-speed-limits": { "en": "Dynamic speed limits", "fi": "Dynaamiset nopeusrajoitukset" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/dynamic-traffic-signs-and-regulations": { "en": "Dynamic traffic signs and regulations", "fi": "Dynaamiset liikennemerkit ja -säännöt" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/e-scooter-sharing-availability": { "en": "E-scooter-sharing Availability", "fi": "Yhteiskäyttöisten sähköpotkulautojen saatavuus" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/e-scooter-sharing-locations-and-stations": { "en": "E-scooter-sharing Locations and stations", "fi": "Yhteiskäyttöisten sähköpotkulautojen sijainnit ja asemat" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/environmental-standards-for-vehicles": { "en": "Environmental standards for vehicles", "fi": "Ajoneuvojen ympäristöstandardit" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/expected-delays": { "en": "Expected delays", "fi": "Tiedossa olevat viivästykset" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/fares": { "en": "Fares", "fi": "Maksut ja tariffit" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/filling-and-charging-stations": { "en": "Filling and charging stations", "fi": "Tankkaus- ja latausasemat" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/freight-and-logistics": { "en": "Freight and logistics", "fi": "Rahti ja logistiikka" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/freight-delivery-regulations": { "en": "Freight delivery regulations", "fi": "Rahdinkuljetusmääräykset" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/general-information-for-trip-planning-": { "en": "General information for trip-planning", "fi": "Yleistä tietoa reittisuunnitteluun" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/geometry": { "en": "Geometry", "fi": "Geometria" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/gradients": { "en": "Gradients", "fi": "Kaltevuudet" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/hours-of-operation": { "en": "Hours of operation", "fi": "Käyttöajat" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/identification-of-tolled-roads": { "en": "Identification of tolled roads", "fi": "Tietullin alaisten teiden yksilöiminen" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/junctions": { "en": "Junctions", "fi": "Liittymät" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/lane-closures-and-access-conditions": { "en": "Lane closures and access conditions", "fi": "Kaistojen sulkemiset ja käyttörajoitukset" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/location-and-conditions-of-charging-points": { "en": "Location and conditions of charging points", "fi": "Latauspisteiden sijainnit ja olosuhteet" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/location-and-conditions-of-filling-stations": { "en": "Location and conditions of filling stations", "fi": "Tankkausasemien sijainnit ja olosuhteet" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/location-and-length-of-queues": { "en": "Location and length of queues", "fi": "Jonojen sijainti ja pituus" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/location-of-delivery-areas": { "en": "Location of delivery areas", "fi": "Lastaus- ja purkausalueiden sijainti" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/location-of-tolling-stations": { "en": "Location of tolling stations", "fi": "Tietulliasemien sijainti" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/locations-and-stations": { "en": "Locations and stations", "fi": "Sijainnit ja asemat" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/long-term-road-works": { "en": "Long-term road works", "fi": "Pitkäaikaiset tietyöt" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/network-closures-diversions": { "en": "Network closures/diversions", "fi": "Verkon suljetut osat ja/tai kiertotiet" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/network-detailed-attributes": { "en": "Network detailed attributes", "fi": "Verkon yksityiskohtaiset tiedot" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/network-geometry-and-lane-character": { "en": "Network geometry and lane character", "fi": "Verkkogeometria ja kaistojen luonne" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/network-topology-and-routes-lines": { "en": "Network topology and routes/lines", "fi": "Verkkotopologia ja reitit/linjat" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/number-of-lanes": { "en": "Number of lanes", "fi": "Kaistojen määrä" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/operational-calendar": { "en": "Operational Calendar", "fi": "Operatiivinen kalenteri" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/other": { "en": "Other", "fi": "Muu" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/other-access-restrictions-and-traffic-regulations": { "en": "Other access restrictions and traffic regulations", "fi": "Muut käyttörajoitukset ja liikennesäännöt" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/other-static-traffic-signs": { "en": "Other static traffic signs", "fi": "Muut staattiset liikennemerkit" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/other-temporary-traffic-management-measures-or-plans": { "en": "Other temporary traffic management measures or plans", "fi": "Muut tilapäiset liikenteenhallintatoimenpiteet tai -suunnitelmat" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/other-traffic-regulations": { "en": "Other traffic regulations", "fi": "Muut liikennesäännöt" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/parameters-needed-to-calculate-costs": { "en": "Parameters needed to calculate costs", "fi": "Kustannusten laskemiseen tarvittavat parametrit" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/parameters-needed-to-calculate-environmental-factors": { "en": "Parameters needed to calculate environmental factors", "fi": "Ympäristötekijöiden laskemiseen tarvittavat parametrit" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/park-and-ride-stops": { "en": "Park and Ride stops", "fi": "Julkisen liikenteen liityntäpysäköinti" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/parking-service-and-rest-area-information": { "en": "Parking, service and rest area information", "fi": "Pysäköinti-, palvelu- ja levähdysalueiden tiedot" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/passenger-classes": { "en": "Passenger classes", "fi": "Matkustajaluokat" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/payment-methods": { "en": "Payment methods", "fi": "Maksutavat" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/payment-methods-for-tolls": { "en": "Payment methods for tolls", "fi": "Tietullien maksutavat" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/pedestrian-accessibility-facilities": { "en": "Pedestrian accessibility facilities", "fi": "Jalankulkijoiden esteettömyyttä tukevat välineet" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/pedestrian-network-data": { "en": "Pedestrian network data", "fi": "Jalankulkuverkon tiedot" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/pedestrian-network-geometry": { "en": "Pedestrian network geometry", "fi": "Jalankulkuverkon geometria" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/permanent-access-restrictions": { "en": "Permanent access restrictions", "fi": "Pysyvät käyttörajoitukset" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/planned-interchanges-between-scheduled-services": { "en": "Planned interchanges between scheduled services", "fi": "Suunnitellut vaihdot säännöllisten palvelujen välillä" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/points-of-interest": { "en": "Points of interest", "fi": "Kohdepisteet" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/poor-road-conditions": { "en": "Poor road conditions", "fi": "Huonokuntoiset tiet" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/predicted-travel-times": { "en": "Predicted travel times", "fi": "Ennustetut matka-ajat" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/provider-data": { "en": "Provider data", "fi": "Palveluntarjoajan tiedot" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/public-transport-non-scheduled-transport": { "en": "Public transport non-scheduled transport", "fi": "Joukkoliikenne, aikatauluttamaton" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/public-transport-scheduled-transport": { "en": "Public transport scheduled transport", "fi": "Joukkoliikenne, säännöllinen" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/purchase-information": { "en": "Purchase information", "fi": "Ostotiedot" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/real-time-estimated-departure-and-arrival-times": { "en": "Real-time estimated departure and arrival times", "fi": "Reaaliaikaiset arvioidut lähtö- ja saapumisajat" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/real-time-traffic-data": { "en": "Real-time traffic data", "fi": "Reaaliaikaiset liikennetiedot" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/reservation-and-purchase-options": { "en": "Reservation and purchase options", "fi": "Varaus- ja ostovaihtoehdot" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/road-classification": { "en": "Road classification", "fi": "Tien luokitus" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/road-closures-and-access-conditions": { "en": "Road closures and access conditions", "fi": "Teiden sulkemiset ja käyttörajoitukset" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/road-events-and-conditions": { "en": "Road events and conditions", "fi": "Tieolosuhteet ja tapahtumat" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/road-weather-conditions": { "en": "Road weather conditions", "fi": "Tieolosuhteet" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/road-width": { "en": "Road width", "fi": "Teiden leveys" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/road-work-information": { "en": "Road work information", "fi": "Tietyötiedot" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/service-and-rest-area-availability": { "en": "Service and rest area availability", "fi": "Palvelu- ja levähdysalueiden saatavuus" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/service-and-rest-area-locations-and-conditions": { "en": "Service and rest area locations and conditions", "fi": "Palvelu- ja levähdysalueiden sijainnit ja olosuhteet" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/service-areas-and-service-times": { "en": "Service areas and service times", "fi": "Palvelualueet ja palveluajat" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/sharing-and-hiring-services": { "en": "Sharing and Hiring Services", "fi": "Vuokraus- ja yhteiskäyttöpalvelut" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/short-term-road-works": { "en": "Short-term road works", "fi": "Lyhytaikaiset tietyöt" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/special-fare-products": { "en": "Special Fare Products", "fi": "Erikoismaksutuotteet" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/speed": { "en": "Speed", "fi": "Nopeus" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/speed-limits": { "en": "Speed limits", "fi": "Nopeusrajoitukset" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/static-road-network-data": { "en": "Static road network data", "fi": "Staattiset tieverkon tiedot" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/static-traffic-signs-and-regulations": { "en": "Static traffic signs and regulations", "fi": "Staattiset liikennemerkit ja -säännöt" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/stop-facilities-accessibility-and-paths-within-facility": { "en": "Stop facilities accessibility and paths within facility", "fi": "Pysäkkipalveluiden esteettömyys ja reitit" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/stop-facilities-geometry-and-map-layout": { "en": "Stop facilities geometry and map layout", "fi": "Pysäkkipalveluiden geometria ja kartta" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/stop-facilities-location-and-features": { "en": "Stop facilities location and features", "fi": "Pysäkkipalveluiden sijainti ja ominaisuudet" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/stop-facilities-status-of-features": { "en": "Stop facilities status of features", "fi": "Pysäkkipalveluiden ominaisuuksien tila" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/timetables-static": { "en": "Timetables static", "fi": "Aikataulut, staattiset" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/toll-information": { "en": "Toll information", "fi": "Tietullitiedot" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/topographic-places": { "en": "Topographic places", "fi": "Topografiset paikat" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/traffic-circulation-plans": { "en": "Traffic circulation plans", "fi": "Liikennevirtasuunnitelmat" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/traffic-data-at-border-crossings-to-third-countries": { "en": "Traffic data at border crossings to third countries", "fi": "Liikennetiedot rajanylityspaikoilla kolmansiin maihin" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/traffic-volume": { "en": "Traffic volume", "fi": "Liikenteen määrä" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/transport-operators": { "en": "Transport operators", "fi": "Liikenteenharjoittajat" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/truck-parking-availability": { "en": "Truck parking availability", "fi": "Kuorma-autopysäköinnin saatavuus" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/truck-parking-locations-and-conditions": { "en": "Truck parking locations and conditions", "fi": "Kuorma-autojen pysäköintipaikat ja -olosuhteet" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/tunnel-access-conditions": { "en": "Tunnel access conditions", "fi": "Tunneleiden käyttörajoitukset" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/tunnel-closures-and-access-conditions": { "en": "Tunnel closures and access conditions", "fi": "Tunneleiden sulkemiset ja käyttörajoitukset" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/vehicle-details": { "en": "Vehicle details", "fi": "Ajoneuvojen tiedot" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/waiting-time-at-border-crossings-to-non-eu-member-states": { "en": "Waiting time at border crossings to non-EU Member States", "fi": "Odotusaika rajanylityspaikoilla EU:n ulkopuolisiin maihin" },
  "https://w3id.org/mobilitydcat-ap/mobility-theme/waterways-and-water-bodies": { "en": "Waterways and water bodies", "fi": "Vesiväylät ja vesistöt" },
}

export function isTopMobilityTheme(obj: unknown): obj is TOP_MOBILITY_THEMES_T {
  return typeof obj === 'string' && TOP_MOBILITY_THEMES.has(obj)
}

export function isSubMobilityTheme(obj: unknown): obj is SUB_MOBILITY_THEMES_T {
  return typeof obj === 'string' && SUB_MOBILITY_THEMES.has(obj)
}