export enum FileFormat {
  FORMAT_7Z = 'http://publications.europa.eu/resource/authority/file-type/7Z',
  FORMAT_AAB = 'http://publications.europa.eu/resource/authority/file-type/AAB',
  FORMAT_AAC = 'http://publications.europa.eu/resource/authority/file-type/AAC',
  FORMAT_AKN4EU_ZIP = 'http://publications.europa.eu/resource/authority/file-type/AKN4EU_ZIP',
  FORMAT_AKN4EU = 'http://publications.europa.eu/resource/authority/file-type/AKN4EU',
  FORMAT_APK = 'http://publications.europa.eu/resource/authority/file-type/APK',
  FORMAT_ARC = 'http://publications.europa.eu/resource/authority/file-type/ARC',
  FORMAT_ARC_GZ = 'http://publications.europa.eu/resource/authority/file-type/ARC_GZ',
  FORMAT_ARJ = 'http://publications.europa.eu/resource/authority/file-type/ARJ',
  FORMAT_AZW = 'http://publications.europa.eu/resource/authority/file-type/AZW',
  FORMAT_APPX = 'http://publications.europa.eu/resource/authority/file-type/APPX',
  FORMAT_MAP_PRVW = 'http://publications.europa.eu/resource/authority/file-type/MAP_PRVW',
  FORMAT_MAP_SRVC = 'http://publications.europa.eu/resource/authority/file-type/MAP_SRVC',
  FORMAT_ARCINFO_COV = 'http://publications.europa.eu/resource/authority/file-type/ARCINFO_COV',
  FORMAT_ARROW_FILE = 'http://publications.europa.eu/resource/authority/file-type/ARROW_FILE',
  FORMAT_ARROW_STREAM = 'http://publications.europa.eu/resource/authority/file-type/ARROW_STREAM',
  FORMAT_ATOM = 'http://publications.europa.eu/resource/authority/file-type/ATOM',
  FORMAT_BITS = 'http://publications.europa.eu/resource/authority/file-type/BITS',
  FORMAT_BWF = 'http://publications.europa.eu/resource/authority/file-type/BWF',
  FORMAT_BIN = 'http://publications.europa.eu/resource/authority/file-type/BIN',
  FORMAT_BMP = 'http://publications.europa.eu/resource/authority/file-type/BMP',
  FORMAT_CSS = 'http://publications.europa.eu/resource/authority/file-type/CSS',
  FORMAT_CSV = 'http://publications.europa.eu/resource/authority/file-type/CSV',
  FORMAT_LAZ = 'http://publications.europa.eu/resource/authority/file-type/LAZ',
  FORMAT_DAPK = 'http://publications.europa.eu/resource/authority/file-type/DAPK',
  FORMAT_DBF = 'http://publications.europa.eu/resource/authority/file-type/DBF',
  FORMAT_DCR = 'http://publications.europa.eu/resource/authority/file-type/DCR',
  FORMAT_DGN = 'http://publications.europa.eu/resource/authority/file-type/DGN',
  FORMAT_DMG = 'http://publications.europa.eu/resource/authority/file-type/DMG',
  FORMAT_DWG = 'http://publications.europa.eu/resource/authority/file-type/DWG',
  FORMAT_DXF = 'http://publications.europa.eu/resource/authority/file-type/DXF',
  FORMAT_DWCA = 'http://publications.europa.eu/resource/authority/file-type/DWCA',
  FORMAT_E00 = 'http://publications.europa.eu/resource/authority/file-type/E00',
  FORMAT_EAR = 'http://publications.europa.eu/resource/authority/file-type/EAR',
  FORMAT_ECW = 'http://publications.europa.eu/resource/authority/file-type/ECW',
  FORMAT_EPUB = 'http://publications.europa.eu/resource/authority/file-type/EPUB',
  FORMAT_ETSI_TSL = 'http://publications.europa.eu/resource/authority/file-type/ETSI_TSL',
  FORMAT_ETSI_XML = 'http://publications.europa.eu/resource/authority/file-type/ETSI_XML',
  FORMAT_EXE = 'http://publications.europa.eu/resource/authority/file-type/EXE',
  FORMAT_EPS = 'http://publications.europa.eu/resource/authority/file-type/EPS',
  FORMAT_GRID_ASCII = 'http://publications.europa.eu/resource/authority/file-type/GRID_ASCII',
  FORMAT_GDB = 'http://publications.europa.eu/resource/authority/file-type/GDB',
  FORMAT_REST = 'http://publications.europa.eu/resource/authority/file-type/REST',
  FORMAT_SHP = 'http://publications.europa.eu/resource/authority/file-type/SHP',
  FORMAT_GRID = 'http://publications.europa.eu/resource/authority/file-type/GRID',
  FORMAT_XLS = 'http://publications.europa.eu/resource/authority/file-type/XLS',
  FORMAT_XLSX = 'http://publications.europa.eu/resource/authority/file-type/XLSX',
  FORMAT_FMX4_ZIP = 'http://publications.europa.eu/resource/authority/file-type/FMX4_ZIP',
  FORMAT_FMX2 = 'http://publications.europa.eu/resource/authority/file-type/FMX2',
  FORMAT_FMX3 = 'http://publications.europa.eu/resource/authority/file-type/FMX3',
  FORMAT_FMX4 = 'http://publications.europa.eu/resource/authority/file-type/FMX4',
  FORMAT_GIF = 'http://publications.europa.eu/resource/authority/file-type/GIF',
  FORMAT_GML = 'http://publications.europa.eu/resource/authority/file-type/GML',
  FORMAT_GZIP = 'http://publications.europa.eu/resource/authority/file-type/GZIP',
  FORMAT_GPX = 'http://publications.europa.eu/resource/authority/file-type/GPX',
  FORMAT_GTFS = 'http://publications.europa.eu/resource/authority/file-type/GTFS',
  FORMAT_GEOJSON = 'http://publications.europa.eu/resource/authority/file-type/GEOJSON',
  FORMAT_GPKG = 'http://publications.europa.eu/resource/authority/file-type/GPKG',
  FORMAT_GEOTIFF = 'http://publications.europa.eu/resource/authority/file-type/GEOTIFF',
  FORMAT_HDF = 'http://publications.europa.eu/resource/authority/file-type/HDF',
  FORMAT_HDT = 'http://publications.europa.eu/resource/authority/file-type/HDT',
  FORMAT_HTML = 'http://publications.europa.eu/resource/authority/file-type/HTML',
  FORMAT_HTML_SIMPL = 'http://publications.europa.eu/resource/authority/file-type/HTML_SIMPL',
  FORMAT_HTML5 = 'http://publications.europa.eu/resource/authority/file-type/HTML5',
  FORMAT_MSG_HTTP = 'http://publications.europa.eu/resource/authority/file-type/MSG_HTTP',
  FORMAT_ICS = 'http://publications.europa.eu/resource/authority/file-type/ICS',
  FORMAT_IMMC_XML = 'http://publications.europa.eu/resource/authority/file-type/IMMC_XML',
  FORMAT_INDD = 'http://publications.europa.eu/resource/authority/file-type/INDD',
  FORMAT_IPA = 'http://publications.europa.eu/resource/authority/file-type/IPA',
  FORMAT_ISO = 'http://publications.europa.eu/resource/authority/file-type/ISO',
  FORMAT_JAR = 'http://publications.europa.eu/resource/authority/file-type/JAR',
  FORMAT_JATS = 'http://publications.europa.eu/resource/authority/file-type/JATS',
  FORMAT_JPEG = 'http://publications.europa.eu/resource/authority/file-type/JPEG',
  FORMAT_JPEG2000 = 'http://publications.europa.eu/resource/authority/file-type/JPEG2000',
  FORMAT_JSON = 'http://publications.europa.eu/resource/authority/file-type/JSON',
  FORMAT_JSON_LD = 'http://publications.europa.eu/resource/authority/file-type/JSON_LD',
  FORMAT_JS = 'http://publications.europa.eu/resource/authority/file-type/JS',
  FORMAT_KML = 'http://publications.europa.eu/resource/authority/file-type/KML',
  FORMAT_KMZ = 'http://publications.europa.eu/resource/authority/file-type/KMZ',
  FORMAT_LAS = 'http://publications.europa.eu/resource/authority/file-type/LAS',
  FORMAT_LEG = 'http://publications.europa.eu/resource/authority/file-type/LEG',
  FORMAT_LHA = 'http://publications.europa.eu/resource/authority/file-type/LHA',
  FORMAT_LPK = 'http://publications.europa.eu/resource/authority/file-type/LPK',
  FORMAT_LEGALHTML = 'http://publications.europa.eu/resource/authority/file-type/LEGALHTML',
  FORMAT_MBOX = 'http://publications.europa.eu/resource/authority/file-type/MBOX',
  FORMAT_MDB = 'http://publications.europa.eu/resource/authority/file-type/MDB',
  FORMAT_METS = 'http://publications.europa.eu/resource/authority/file-type/METS',
  FORMAT_METS_ZIP = 'http://publications.europa.eu/resource/authority/file-type/METS_ZIP',
  FORMAT_MHTML = 'http://publications.europa.eu/resource/authority/file-type/MHTML',
  FORMAT_MIF_MID = 'http://publications.europa.eu/resource/authority/file-type/MIF_MID',
  FORMAT_MOP = 'http://publications.europa.eu/resource/authority/file-type/MOP',
  FORMAT_MOV = 'http://publications.europa.eu/resource/authority/file-type/MOV',
  FORMAT_MP3 = 'http://publications.europa.eu/resource/authority/file-type/MP3',
  FORMAT_MPEG2 = 'http://publications.europa.eu/resource/authority/file-type/MPEG2',
  FORMAT_MPEG4 = 'http://publications.europa.eu/resource/authority/file-type/MPEG4',
  FORMAT_MPEG4_AVC = 'http://publications.europa.eu/resource/authority/file-type/MPEG4_AVC',
  FORMAT_MSI = 'http://publications.europa.eu/resource/authority/file-type/MSI',
  FORMAT_MXD = 'http://publications.europa.eu/resource/authority/file-type/MXD',
  FORMAT_TAB = 'http://publications.europa.eu/resource/authority/file-type/TAB',
  FORMAT_TAB_RSTR = 'http://publications.europa.eu/resource/authority/file-type/TAB_RSTR',
  FORMAT_MARKDOWN = 'http://publications.europa.eu/resource/authority/file-type/MARKDOWN',
  FORMAT_MATHML = 'http://publications.europa.eu/resource/authority/file-type/MATHML',
  FORMAT_MOBI = 'http://publications.europa.eu/resource/authority/file-type/MOBI',
  FORMAT_MRSID = 'http://publications.europa.eu/resource/authority/file-type/MRSID',
  FORMAT_N3 = 'http://publications.europa.eu/resource/authority/file-type/N3',
  FORMAT_NETCDF = 'http://publications.europa.eu/resource/authority/file-type/NETCDF',
  FORMAT_OAPK = 'http://publications.europa.eu/resource/authority/file-type/OAPK',
  FORMAT_ODF = 'http://publications.europa.eu/resource/authority/file-type/ODF',
  FORMAT_ODP = 'http://publications.europa.eu/resource/authority/file-type/ODP',
  FORMAT_ODS = 'http://publications.europa.eu/resource/authority/file-type/ODS',
  FORMAT_ODT = 'http://publications.europa.eu/resource/authority/file-type/ODT',
  FORMAT_OVF = 'http://publications.europa.eu/resource/authority/file-type/OVF',
  FORMAT_OWL = 'http://publications.europa.eu/resource/authority/file-type/OWL',
  FORMAT_OCTET = 'http://publications.europa.eu/resource/authority/file-type/OCTET',
  FORMAT_ODC = 'http://publications.europa.eu/resource/authority/file-type/ODC',
  FORMAT_ODB = 'http://publications.europa.eu/resource/authority/file-type/ODB',
  FORMAT_ODG = 'http://publications.europa.eu/resource/authority/file-type/ODG',
  FORMAT_DMP = 'http://publications.europa.eu/resource/authority/file-type/DMP',
  FORMAT_PDF = 'http://publications.europa.eu/resource/authority/file-type/PDF',
  FORMAT_PDFA1A = 'http://publications.europa.eu/resource/authority/file-type/PDFA1A',
  FORMAT_PDFA1B = 'http://publications.europa.eu/resource/authority/file-type/PDFA1B',
  FORMAT_PDFA2A = 'http://publications.europa.eu/resource/authority/file-type/PDFA2A',
  FORMAT_PDFA2B = 'http://publications.europa.eu/resource/authority/file-type/PDFA2B',
  FORMAT_PDFUA = 'http://publications.europa.eu/resource/authority/file-type/PDFUA',
  FORMAT_PDFX = 'http://publications.europa.eu/resource/authority/file-type/PDFX',
  FORMAT_PDFX1A = 'http://publications.europa.eu/resource/authority/file-type/PDFX1A',
  FORMAT_PDFX2A = 'http://publications.europa.eu/resource/authority/file-type/PDFX2A',
  FORMAT_PDFX4 = 'http://publications.europa.eu/resource/authority/file-type/PDFX4',
  FORMAT_PDF1X = 'http://publications.europa.eu/resource/authority/file-type/PDF1X',
  FORMAT_PDFA3 = 'http://publications.europa.eu/resource/authority/file-type/PDFA3',
  FORMAT_PNG = 'http://publications.europa.eu/resource/authority/file-type/PNG',
  FORMAT_PS = 'http://publications.europa.eu/resource/authority/file-type/PS',
  FORMAT_PSD = 'http://publications.europa.eu/resource/authority/file-type/PSD',
  FORMAT_PWP = 'http://publications.europa.eu/resource/authority/file-type/PWP',
  FORMAT_PARQUET = 'http://publications.europa.eu/resource/authority/file-type/PARQUET',
  FORMAT_PL = 'http://publications.europa.eu/resource/authority/file-type/PL',
  FORMAT_TXT = 'http://publications.europa.eu/resource/authority/file-type/TXT',
  FORMAT_PPSX = 'http://publications.europa.eu/resource/authority/file-type/PPSX',
  FORMAT_PPT = 'http://publications.europa.eu/resource/authority/file-type/PPT',
  FORMAT_PPTX = 'http://publications.europa.eu/resource/authority/file-type/PPTX',
  FORMAT_PPS = 'http://publications.europa.eu/resource/authority/file-type/PPS',
  FORMAT_OP_DATPRO = 'http://publications.europa.eu/resource/authority/file-type/OP_DATPRO',
  FORMAT_QGS = 'http://publications.europa.eu/resource/authority/file-type/QGS',
  FORMAT_RAR = 'http://publications.europa.eu/resource/authority/file-type/RAR',
  FORMAT_RDF = 'http://publications.europa.eu/resource/authority/file-type/RDF',
  FORMAT_RDF_N_QUADS = 'http://publications.europa.eu/resource/authority/file-type/RDF_N_QUADS',
  FORMAT_RDF_N_TRIPLES = 'http://publications.europa.eu/resource/authority/file-type/RDF_N_TRIPLES',
  FORMAT_RDF_THRIFT = 'http://publications.europa.eu/resource/authority/file-type/RDF_THRIFT',
  FORMAT_RDF_TRIG = 'http://publications.europa.eu/resource/authority/file-type/RDF_TRIG',
  FORMAT_RDF_TRIX = 'http://publications.europa.eu/resource/authority/file-type/RDF_TRIX',
  FORMAT_RDF_TURTLE = 'http://publications.europa.eu/resource/authority/file-type/RDF_TURTLE',
  FORMAT_RDF_XML = 'http://publications.europa.eu/resource/authority/file-type/RDF_XML',
  FORMAT_RDFA = 'http://publications.europa.eu/resource/authority/file-type/RDFA',
  FORMAT_RPM = 'http://publications.europa.eu/resource/authority/file-type/RPM',
  FORMAT_RSS = 'http://publications.europa.eu/resource/authority/file-type/RSS',
  FORMAT_RTF = 'http://publications.europa.eu/resource/authority/file-type/RTF',
  FORMAT_SDMX = 'http://publications.europa.eu/resource/authority/file-type/SDMX',
  FORMAT_SGML = 'http://publications.europa.eu/resource/authority/file-type/SGML',
  FORMAT_DTD_SGML = 'http://publications.europa.eu/resource/authority/file-type/DTD_SGML',
  FORMAT_SKOS_XML = 'http://publications.europa.eu/resource/authority/file-type/SKOS_XML',
  FORMAT_SPARQLQ = 'http://publications.europa.eu/resource/authority/file-type/SPARQLQ',
  FORMAT_SPARQLQRES = 'http://publications.europa.eu/resource/authority/file-type/SPARQLQRES',
  FORMAT_SQL = 'http://publications.europa.eu/resource/authority/file-type/SQL',
  FORMAT_SVG = 'http://publications.europa.eu/resource/authority/file-type/SVG',
  FORMAT_SWM = 'http://publications.europa.eu/resource/authority/file-type/SWM',
  FORMAT_STL = 'http://publications.europa.eu/resource/authority/file-type/STL',
  FORMAT_TAR = 'http://publications.europa.eu/resource/authority/file-type/TAR',
  FORMAT_TAR_GZ = 'http://publications.europa.eu/resource/authority/file-type/TAR_GZ',
  FORMAT_TAR_XZ = 'http://publications.europa.eu/resource/authority/file-type/TAR_XZ',
  FORMAT_TIFF = 'http://publications.europa.eu/resource/authority/file-type/TIFF',
  FORMAT_TIFF_FX = 'http://publications.europa.eu/resource/authority/file-type/TIFF_FX',
  FORMAT_TMX = 'http://publications.europa.eu/resource/authority/file-type/TMX',
  FORMAT_TSV = 'http://publications.europa.eu/resource/authority/file-type/TSV',
  FORMAT_THRIFT_JSON = 'http://publications.europa.eu/resource/authority/file-type/THRIFT_JSON',
  FORMAT_THRIFT_BINARY = 'http://publications.europa.eu/resource/authority/file-type/THRIFT_BINARY',
  FORMAT_THRIFT_COMPACT = 'http://publications.europa.eu/resource/authority/file-type/THRIFT_COMPACT',
  FORMAT_UNGEN = 'http://publications.europa.eu/resource/authority/file-type/UNGEN',
  FORMAT_WAR = 'http://publications.europa.eu/resource/authority/file-type/WAR',
  FORMAT_WARC = 'http://publications.europa.eu/resource/authority/file-type/WARC',
  FORMAT_WARC_GZ = 'http://publications.europa.eu/resource/authority/file-type/WARC_GZ',
  FORMAT_WAV = 'http://publications.europa.eu/resource/authority/file-type/WAV',
  FORMAT_WCS_SRVC = 'http://publications.europa.eu/resource/authority/file-type/WCS_SRVC',
  FORMAT_WFS_SRVC = 'http://publications.europa.eu/resource/authority/file-type/WFS_SRVC',
  FORMAT_WIM = 'http://publications.europa.eu/resource/authority/file-type/WIM',
  FORMAT_WMS_SRVC = 'http://publications.europa.eu/resource/authority/file-type/WMS_SRVC',
  FORMAT_WMTS_SRVC = 'http://publications.europa.eu/resource/authority/file-type/WMTS_SRVC',
  FORMAT_WEBP = 'http://publications.europa.eu/resource/authority/file-type/WEBP',
  FORMAT_DOC = 'http://publications.europa.eu/resource/authority/file-type/DOC',
  FORMAT_DOCX = 'http://publications.europa.eu/resource/authority/file-type/DOCX',
  FORMAT_WORLD = 'http://publications.europa.eu/resource/authority/file-type/WORLD',
  FORMAT_XHTML = 'http://publications.europa.eu/resource/authority/file-type/XHTML',
  FORMAT_XHTML_SIMPL = 'http://publications.europa.eu/resource/authority/file-type/XHTML_SIMPL',
  FORMAT_XHTML5 = 'http://publications.europa.eu/resource/authority/file-type/XHTML5',
  FORMAT_XLIFF = 'http://publications.europa.eu/resource/authority/file-type/XLIFF',
  FORMAT_XLSB = 'http://publications.europa.eu/resource/authority/file-type/XLSB',
  FORMAT_XLSM = 'http://publications.europa.eu/resource/authority/file-type/XLSM',
  FORMAT_XML = 'http://publications.europa.eu/resource/authority/file-type/XML',
  FORMAT_DTD_XML = 'http://publications.europa.eu/resource/authority/file-type/DTD_XML',
  FORMAT_SCHEMA_XML = 'http://publications.europa.eu/resource/authority/file-type/SCHEMA_XML',
  FORMAT_XSLFO = 'http://publications.europa.eu/resource/authority/file-type/XSLFO',
  FORMAT_XSLT = 'http://publications.europa.eu/resource/authority/file-type/XSLT',
  FORMAT_XYZ = 'http://publications.europa.eu/resource/authority/file-type/XYZ',
  FORMAT_YAML = 'http://publications.europa.eu/resource/authority/file-type/YAML',
  FORMAT_Z = 'http://publications.europa.eu/resource/authority/file-type/Z',
  FORMAT_ZIP = 'http://publications.europa.eu/resource/authority/file-type/ZIP',
  FORMAT_GMZ = 'http://publications.europa.eu/resource/authority/file-type/GMZ',
  FORMAT_ISO_ZIP = 'http://publications.europa.eu/resource/authority/file-type/ISO_ZIP',
  FORMAT_BZIP2 = 'http://publications.europa.eu/resource/authority/file-type/BZIP2',
  FORMAT_DEB = 'http://publications.europa.eu/resource/authority/file-type/DEB',
  FORMAT_EFORMS_XML = 'http://publications.europa.eu/resource/authority/file-type/EFORMS_XML',
  FORMAT_LZIP = 'http://publications.europa.eu/resource/authority/file-type/LZIP',
  FORMAT_LZMA = 'http://publications.europa.eu/resource/authority/file-type/LZMA',
  FORMAT_LZO = 'http://publications.europa.eu/resource/authority/file-type/LZO',
  FORMAT_SB3 = 'http://publications.europa.eu/resource/authority/file-type/SB3',
  FORMAT_XZ = 'http://publications.europa.eu/resource/authority/file-type/XZ',
}

const fileFormatLabels: Record<FileFormat, string> = {
    [FileFormat.FORMAT_7Z]: '7z',
    [FileFormat.FORMAT_AAB]: 'AAB',
    [FileFormat.FORMAT_AAC]: 'AAC',
    [FileFormat.FORMAT_AKN4EU_ZIP]: 'AKN4EU ZIP',
    [FileFormat.FORMAT_AKN4EU]: 'AKN4EU file',
    [FileFormat.FORMAT_APK]: 'APK',
    [FileFormat.FORMAT_ARC]: 'ARC',
    [FileFormat.FORMAT_ARC_GZ]: 'ARC GZ',
    [FileFormat.FORMAT_ARJ]: 'ARJ',
    [FileFormat.FORMAT_AZW]: 'Amazon Kindle eBook',
    [FileFormat.FORMAT_APPX]: 'AppX',
    [FileFormat.FORMAT_MAP_PRVW]: 'ArcGIS Map Preview',
    [FileFormat.FORMAT_MAP_SRVC]: 'ArcGIS Map Service',
    [FileFormat.FORMAT_ARCINFO_COV]: 'ArcInfo coverage',
    [FileFormat.FORMAT_ARROW_FILE]: 'Arrow file',
    [FileFormat.FORMAT_ARROW_STREAM]: 'Arrow stream',
    [FileFormat.FORMAT_ATOM]: 'Atom Feed',
    [FileFormat.FORMAT_BITS]: 'BITS XML',
    [FileFormat.FORMAT_BWF]: 'BWF',
    [FileFormat.FORMAT_BIN]: 'Binary Data',
    [FileFormat.FORMAT_BMP]: 'Bitmap Image File',
    [FileFormat.FORMAT_CSS]: 'CSS',
    [FileFormat.FORMAT_CSV]: 'CSV',
    [FileFormat.FORMAT_LAZ]: 'Compressed LAS file',
    [FileFormat.FORMAT_DAPK]: 'DAPK',
    [FileFormat.FORMAT_DBF]: 'DBF',
    [FileFormat.FORMAT_DCR]: 'DCR File',
    [FileFormat.FORMAT_DGN]: 'DGN',
    [FileFormat.FORMAT_DMG]: 'DMG',
    [FileFormat.FORMAT_DWG]: 'DWG',
    [FileFormat.FORMAT_DXF]: 'DXF',
    [FileFormat.FORMAT_DWCA]: 'DwC-A',
    [FileFormat.FORMAT_E00]: 'E00',
    [FileFormat.FORMAT_EAR]: 'EAR',
    [FileFormat.FORMAT_ECW]: 'ECW',
    [FileFormat.FORMAT_EPUB]: 'EPUB',
    [FileFormat.FORMAT_ETSI_TSL]: 'ETSI TSL',
    [FileFormat.FORMAT_ETSI_XML]: 'ETSI signature validation report',
    [FileFormat.FORMAT_EXE]: 'EXE',
    [FileFormat.FORMAT_EPS]: 'Encapsulated Postscript',
    [FileFormat.FORMAT_GRID_ASCII]: 'Esri ASCII grid',
    [FileFormat.FORMAT_GDB]: 'Esri File Geodatabase',
    [FileFormat.FORMAT_REST]: 'Esri REST',
    [FileFormat.FORMAT_SHP]: 'Esri Shape',
    [FileFormat.FORMAT_GRID]: 'Esri binary grid',
    [FileFormat.FORMAT_XLS]: 'Excel XLS',
    [FileFormat.FORMAT_XLSX]: 'Excel XLSX',
    [FileFormat.FORMAT_FMX4_ZIP]: 'FMX4 ZIP',
    [FileFormat.FORMAT_FMX2]: 'Formex 2',
    [FileFormat.FORMAT_FMX3]: 'Formex 3',
    [FileFormat.FORMAT_FMX4]: 'Formex 4',
    [FileFormat.FORMAT_GIF]: 'GIF',
    [FileFormat.FORMAT_GML]: 'GML',
    [FileFormat.FORMAT_GZIP]: 'GNU zip',
    [FileFormat.FORMAT_GPX]: 'GPX',
    [FileFormat.FORMAT_GTFS]: 'GTFS',
    [FileFormat.FORMAT_GEOJSON]: 'GeoJSON',
    [FileFormat.FORMAT_GPKG]: 'GeoPackage',
    [FileFormat.FORMAT_GEOTIFF]: 'GeoTIFF',
    [FileFormat.FORMAT_HDF]: 'HDF',
    [FileFormat.FORMAT_HDT]: 'HDT',
    [FileFormat.FORMAT_HTML]: 'HTML',
    [FileFormat.FORMAT_HTML_SIMPL]: 'HTML simplified',
    [FileFormat.FORMAT_HTML5]: 'HTML5',
    [FileFormat.FORMAT_MSG_HTTP]: 'HTTP Message',
    [FileFormat.FORMAT_ICS]: 'ICalendar',
    [FileFormat.FORMAT_IMMC_XML]: 'IMMC XML message',
    [FileFormat.FORMAT_INDD]: 'INDD',
    [FileFormat.FORMAT_IPA]: 'IPA',
    [FileFormat.FORMAT_ISO]: 'ISO image',
    [FileFormat.FORMAT_JAR]: 'JAR',
    [FileFormat.FORMAT_JATS]: 'JATS XML',
    [FileFormat.FORMAT_JPEG]: 'JPEG',
    [FileFormat.FORMAT_JPEG2000]: 'JPEG 2000',
    [FileFormat.FORMAT_JSON]: 'JSON',
    [FileFormat.FORMAT_JSON_LD]: 'JSON-LD',
    [FileFormat.FORMAT_JS]: 'JavaScript',
    [FileFormat.FORMAT_KML]: 'KML',
    [FileFormat.FORMAT_KMZ]: 'KMZ',
    [FileFormat.FORMAT_LAS]: 'LASer file',
    [FileFormat.FORMAT_LEG]: 'LEG',
    [FileFormat.FORMAT_LHA]: 'LHA',
    [FileFormat.FORMAT_LPK]: 'Layer package',
    [FileFormat.FORMAT_LEGALHTML]: 'LegalHTML',
    [FileFormat.FORMAT_MBOX]: 'MBOX',
    [FileFormat.FORMAT_MDB]: 'MDB',
    [FileFormat.FORMAT_METS]: 'METS XML',
    [FileFormat.FORMAT_METS_ZIP]: 'METS package',
    [FileFormat.FORMAT_MHTML]: 'MHTML',
    [FileFormat.FORMAT_MIF_MID]: 'MIF/MID',
    [FileFormat.FORMAT_MOP]: 'MOP',
    [FileFormat.FORMAT_MOV]: 'MOV',
    [FileFormat.FORMAT_MP3]: 'MP3',
    [FileFormat.FORMAT_MPEG2]: 'MPEG-2',
    [FileFormat.FORMAT_MPEG4]: 'MPEG-4',
    [FileFormat.FORMAT_MPEG4_AVC]: 'MPEG-4 AVC',
    [FileFormat.FORMAT_MSI]: 'MSI',
    [FileFormat.FORMAT_MXD]: 'MXD',
    [FileFormat.FORMAT_TAB]: 'MapInfo TAB file',
    [FileFormat.FORMAT_TAB_RSTR]: 'MapInfo TAB raster file',
    [FileFormat.FORMAT_MARKDOWN]: 'Markdown',
    [FileFormat.FORMAT_MATHML]: 'MathML',
    [FileFormat.FORMAT_MOBI]: 'Mobipocket eBook',
    [FileFormat.FORMAT_MRSID]: 'MrSID',
    [FileFormat.FORMAT_N3]: 'N3',
    [FileFormat.FORMAT_NETCDF]: 'NetCDF',
    [FileFormat.FORMAT_OAPK]: 'OAPK',
    [FileFormat.FORMAT_ODF]: 'ODF',
    [FileFormat.FORMAT_ODP]: 'ODP',
    [FileFormat.FORMAT_ODS]: 'ODS',
    [FileFormat.FORMAT_ODT]: 'ODT',
    [FileFormat.FORMAT_OVF]: 'OVF',
    [FileFormat.FORMAT_OWL]: 'OWL',
    [FileFormat.FORMAT_OCTET]: 'Octet Stream',
    [FileFormat.FORMAT_ODC]: 'OpenDocument Chart',
    [FileFormat.FORMAT_ODB]: 'OpenDocument Database',
    [FileFormat.FORMAT_ODG]: 'OpenDocument Image',
    [FileFormat.FORMAT_DMP]: 'Oracle Dump',
    [FileFormat.FORMAT_PDF]: 'PDF',
    [FileFormat.FORMAT_PDFA1A]: 'PDF/A-1a',
    [FileFormat.FORMAT_PDFA1B]: 'PDF/A-1b',
    [FileFormat.FORMAT_PDFA2A]: 'PDF/A-2a',
    [FileFormat.FORMAT_PDFA2B]: 'PDF/A-2b',
    [FileFormat.FORMAT_PDFUA]: 'PDF/UA',
    [FileFormat.FORMAT_PDFX]: 'PDF/X',
    [FileFormat.FORMAT_PDFX1A]: 'PDF/X-1a',
    [FileFormat.FORMAT_PDFX2A]: 'PDF/X-2a',
    [FileFormat.FORMAT_PDFX4]: 'PDF/X-4',
    [FileFormat.FORMAT_PDF1X]: 'PDF1X',
    [FileFormat.FORMAT_PDFA3]: 'PDFA-3',
    [FileFormat.FORMAT_PNG]: 'PNG',
    [FileFormat.FORMAT_PS]: 'PS',
    [FileFormat.FORMAT_PSD]: 'PSD',
    [FileFormat.FORMAT_PWP]: 'PWP',
    [FileFormat.FORMAT_PARQUET]: 'Parquet',
    [FileFormat.FORMAT_PL]: 'Perl script',
    [FileFormat.FORMAT_TXT]: 'Plain text',
    [FileFormat.FORMAT_PPSX]: 'PowerPoint PPSX',
    [FileFormat.FORMAT_PPT]: 'PowerPoint PPT',
    [FileFormat.FORMAT_PPTX]: 'PowerPoint PPTX',
    [FileFormat.FORMAT_PPS]: 'PowerPoint Slide Show',
    [FileFormat.FORMAT_OP_DATPRO]: 'Alustavat tiedot',
    [FileFormat.FORMAT_QGS]: 'QGS',
    [FileFormat.FORMAT_RAR]: 'RAR',
    [FileFormat.FORMAT_RDF]: 'RDF',
    [FileFormat.FORMAT_RDF_N_QUADS]: 'RDF N-Quads',
    [FileFormat.FORMAT_RDF_N_TRIPLES]: 'RDF N-Triples',
    [FileFormat.FORMAT_RDF_THRIFT]: 'RDF Thrift',
    [FileFormat.FORMAT_RDF_TRIG]: 'RDF TriG',
    [FileFormat.FORMAT_RDF_TRIX]: 'RDF TriX',
    [FileFormat.FORMAT_RDF_TURTLE]: 'RDF Turtle',
    [FileFormat.FORMAT_RDF_XML]: 'RDF XML',
    [FileFormat.FORMAT_RDFA]: 'RDFa',
    [FileFormat.FORMAT_RPM]: 'RPM',
    [FileFormat.FORMAT_RSS]: 'RSS feed',
    [FileFormat.FORMAT_RTF]: 'RTF',
    [FileFormat.FORMAT_SDMX]: 'SDMX',
    [FileFormat.FORMAT_SGML]: 'SGML',
    [FileFormat.FORMAT_DTD_SGML]: 'SGML DTD',
    [FileFormat.FORMAT_SKOS_XML]: 'SKOS',
    [FileFormat.FORMAT_SPARQLQ]: 'SPARQL',
    [FileFormat.FORMAT_SPARQLQRES]: 'SPARQL results',
    [FileFormat.FORMAT_SQL]: 'SQL',
    [FileFormat.FORMAT_SVG]: 'SVG',
    [FileFormat.FORMAT_SWM]: 'SWM',
    [FileFormat.FORMAT_STL]: 'StL',
    [FileFormat.FORMAT_TAR]: 'TAR',
    [FileFormat.FORMAT_TAR_GZ]: 'TAR GZ',
    [FileFormat.FORMAT_TAR_XZ]: 'TAR XZ',
    [FileFormat.FORMAT_TIFF]: 'TIFF',
    [FileFormat.FORMAT_TIFF_FX]: 'TIFF FX',
    [FileFormat.FORMAT_TMX]: 'TMX',
    [FileFormat.FORMAT_TSV]: 'TSV',
    [FileFormat.FORMAT_THRIFT_JSON]: 'Thrift JSON',
    [FileFormat.FORMAT_THRIFT_BINARY]: 'Thrift binary',
    [FileFormat.FORMAT_THRIFT_COMPACT]: 'Thrift compact',
    [FileFormat.FORMAT_UNGEN]: 'Ungen',
    [FileFormat.FORMAT_WAR]: 'WAR',
    [FileFormat.FORMAT_WARC]: 'WARC',
    [FileFormat.FORMAT_WARC_GZ]: 'WARC GZ',
    [FileFormat.FORMAT_WAV]: 'WAV',
    [FileFormat.FORMAT_WCS_SRVC]: 'WCS',
    [FileFormat.FORMAT_WFS_SRVC]: 'WFS',
    [FileFormat.FORMAT_WIM]: 'WIM',
    [FileFormat.FORMAT_WMS_SRVC]: 'WMS',
    [FileFormat.FORMAT_WMTS_SRVC]: 'WMTS',
    [FileFormat.FORMAT_WEBP]: 'WebP',
    [FileFormat.FORMAT_DOC]: 'Word DOC',
    [FileFormat.FORMAT_DOCX]: 'Word DOCX',
    [FileFormat.FORMAT_WORLD]: 'World file',
    [FileFormat.FORMAT_XHTML]: 'XHTML',
    [FileFormat.FORMAT_XHTML_SIMPL]: 'XHTML simplified',
    [FileFormat.FORMAT_XHTML5]: 'XHTML5',
    [FileFormat.FORMAT_XLIFF]: 'XLIFF',
    [FileFormat.FORMAT_XLSB]: 'XLSB',
    [FileFormat.FORMAT_XLSM]: 'XLSM',
    [FileFormat.FORMAT_XML]: 'XML',
    [FileFormat.FORMAT_DTD_XML]: 'XML DTD',
    [FileFormat.FORMAT_SCHEMA_XML]: 'XML schema',
    [FileFormat.FORMAT_XSLFO]: 'XSL-FO',
    [FileFormat.FORMAT_XSLT]: 'XSLT',
    [FileFormat.FORMAT_XYZ]: 'XYZ Chemical File',
    [FileFormat.FORMAT_YAML]: 'YAML',
    [FileFormat.FORMAT_Z]: 'Z',
    [FileFormat.FORMAT_ZIP]: 'ZIP',
    [FileFormat.FORMAT_GMZ]: 'Zipped GML',
    [FileFormat.FORMAT_ISO_ZIP]: 'Zipped ISO image',
    [FileFormat.FORMAT_BZIP2]: 'bzip2',
    [FileFormat.FORMAT_DEB]: 'deb',
    [FileFormat.FORMAT_EFORMS_XML]: 'eForms XML',
    [FileFormat.FORMAT_LZIP]: 'lzip',
    [FileFormat.FORMAT_LZMA]: 'lzma',
    [FileFormat.FORMAT_LZO]: 'lzo',
    [FileFormat.FORMAT_SB3]: 'sb3',
    [FileFormat.FORMAT_XZ]: 'xz',
}

export class FileFormatOption {
  readonly label: string;
  readonly value: FileFormat;

  constructor(label: string, value: FileFormat) {
    this.label = label;
    this.value = value;
  }

  static fromFileFormat(fileFormat: FileFormat): FileFormatOption {
    return new FileFormatOption(fileFormatLabels[fileFormat], fileFormat);
  }
}