services:
  ckan:
    image: local_catalog_ckan_dev:latest
    ports:
      - "${CKAN_PORT}:${CKAN_PORT}"
      - "${CKAN_DATAPUSHER_PORT}:${CKAN_DATAPUSHER_PORT}"
    depends_on:
      postgresql:
        condition: service_started
      solr:
        condition: service_started
      redis:
        condition: service_started
    env_file:
      - .env_postgresql_common
      - .env_solr_common
      - .env_ckan_common
      - .env_ckan
      - .env_entra
  postgresql:
    image: local_catalog_postgresql:latest
    ports:
      - "5432:5432"
    env_file:
      - .env_postgresql_common
      - .env_postgresql
    command: [ "postgres", "-c", "config_file=/etc/postgresql/postgresql.conf" ]
  solr:
    image: local_catalog_solr:latest
    ports:
      - "${SOLR_PORT}:${SOLR_PORT}"
    env_file:
      - .env_solr_common
  nginx:
    image: local_catalog_nginx:latest
    ports:
      - "8080:80"
    env_file:
      - .env_ckan_common
      - .env_nginx
  redis:
    image: redis:7.4.0
