/**
 * Python script to fetch the MOBILITY_THEME_TREE values:
 *
 * g = rdflib.Graph()
 * g.parse('https://mobilitydcat-ap.github.io/controlled-vocabularies/mobility-theme/latest/mobility-theme.ttl')
 * for top_concept in g.subjects(rdflib.namespace.SKOS.broader, rdflib.URIRef('https://w3id.org/mobilitydcat-ap/mobility-theme/data-content-category')):
 *     sub_concepts = [sub_concept for sub_concept in g.subjects(rdflib.namespace.SKOS.broader, top_concept)]
 *     print(f'"{top_concept}": [')
 *     for cub_concept in sub_concepts:
 *         print(f'"{cub_concept}",')
 *     print('],')
 */
export const MOBILITY_THEME_TREE = {
  "https://w3id.org/mobilitydcat-ap/mobility-theme/air-and-space-travel": [
  ],
  "https://w3id.org/mobilitydcat-ap/mobility-theme/cycle-network-data": [
    "https://w3id.org/mobilitydcat-ap/mobility-theme/network-closures-diversions",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/network-detailed-attributes",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/network-geometry-and-lane-character",
  ],
  "https://w3id.org/mobilitydcat-ap/mobility-theme/dynamic-traffic-signs-and-regulations": [
    "https://w3id.org/mobilitydcat-ap/mobility-theme/bridge-closures-and-access-conditions",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/direction-of-travel-on-reversible-lanes",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/dynamic-overtaking-bans-on-heavy-goods-vehicles",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/dynamic-speed-limits",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/lane-closures-and-access-conditions",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/other-access-restrictions-and-traffic-regulations",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/other-temporary-traffic-management-measures-or-plans",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/road-closures-and-access-conditions",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/tunnel-closures-and-access-conditions",
  ],
  "https://w3id.org/mobilitydcat-ap/mobility-theme/filling-and-charging-stations": [
    "https://w3id.org/mobilitydcat-ap/mobility-theme/availability-of-charging-points-for-electric-vehicles",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/availability-of-filling-stations",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/location-and-conditions-of-charging-points",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/location-and-conditions-of-filling-stations",
  ],
  "https://w3id.org/mobilitydcat-ap/mobility-theme/freight-and-logistics": [
    "https://w3id.org/mobilitydcat-ap/mobility-theme/availability-of-delivery-areas",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/freight-delivery-regulations",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/location-of-delivery-areas",
  ],
  "https://w3id.org/mobilitydcat-ap/mobility-theme/general-information-for-trip-planning-": [
    "https://w3id.org/mobilitydcat-ap/mobility-theme/address-identifiers",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/parameters-needed-to-calculate-costs",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/parameters-needed-to-calculate-environmental-factors",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/points-of-interest",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/topographic-places",
  ],
  "https://w3id.org/mobilitydcat-ap/mobility-theme/other": [
  ],
  "https://w3id.org/mobilitydcat-ap/mobility-theme/parking-service-and-rest-area-information": [
    "https://w3id.org/mobilitydcat-ap/mobility-theme/bike-parking-locations",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/car-parking-availability",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/car-parking-locations-and-conditions",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/park-and-ride-stops",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/service-and-rest-area-availability",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/service-and-rest-area-locations-and-conditions",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/truck-parking-availability",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/truck-parking-locations-and-conditions",
  ],
  "https://w3id.org/mobilitydcat-ap/mobility-theme/pedestrian-network-data": [
    "https://w3id.org/mobilitydcat-ap/mobility-theme/pedestrian-accessibility-facilities",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/pedestrian-network-geometry",
  ],
  "https://w3id.org/mobilitydcat-ap/mobility-theme/public-transport-non-scheduled-transport": [
    "https://w3id.org/mobilitydcat-ap/mobility-theme/accesibility-information-for-vehicles",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/environmental-standards-for-vehicles",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/fares",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/locations-and-stations",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/provider-data",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/reservation-and-purchase-options",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/service-areas-and-service-times",
  ],
  "https://w3id.org/mobilitydcat-ap/mobility-theme/public-transport-scheduled-transport": [
    "https://w3id.org/mobilitydcat-ap/mobility-theme/basic-commercial-conditions",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/basic-common-standard-fares",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/common-fare-products",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/connection-links",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/disruptions-delays-cancellations",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/environmental-standards-for-vehicles",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/hours-of-operation",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/network-topology-and-routes-lines",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/operational-calendar",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/passenger-classes",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/planned-interchanges-between-scheduled-services",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/purchase-information",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/real-time-estimated-departure-and-arrival-times",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/special-fare-products",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/stop-facilities-accessibility-and-paths-within-facility",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/stop-facilities-geometry-and-map-layout",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/stop-facilities-location-and-features",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/stop-facilities-status-of-features",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/timetables-static",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/transport-operators",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/vehicle-details",
  ],
  "https://w3id.org/mobilitydcat-ap/mobility-theme/real-time-traffic-data": [
    "https://w3id.org/mobilitydcat-ap/mobility-theme/current-travel-times",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/expected-delays",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/location-and-length-of-queues",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/predicted-travel-times",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/speed",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/traffic-data-at-border-crossings-to-third-countries",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/traffic-volume",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/waiting-time-at-border-crossings-to-non-eu-member-states",
  ],
  "https://w3id.org/mobilitydcat-ap/mobility-theme/road-events-and-conditions": [
    "https://w3id.org/mobilitydcat-ap/mobility-theme/accidents-and-incidents",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/poor-road-conditions",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/road-weather-conditions",
  ],
  "https://w3id.org/mobilitydcat-ap/mobility-theme/road-work-information": [
    "https://w3id.org/mobilitydcat-ap/mobility-theme/long-term-road-works",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/short-term-road-works",
  ],
  "https://w3id.org/mobilitydcat-ap/mobility-theme/sharing-and-hiring-services": [
    "https://w3id.org/mobilitydcat-ap/mobility-theme/bike-hiring-availability",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/bike-hiring-stations",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/bike-sharing-availability",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/bike-sharing-locations-and-stations",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/car-hiring-availability",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/car-hiring-stations",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/car-sharing-availability",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/car-sharing-locations-and-stations",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/e-scooter-sharing-availability",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/e-scooter-sharing-locations-and-stations",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/environmental-standards-for-vehicles",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/payment-methods",
  ],
  "https://w3id.org/mobilitydcat-ap/mobility-theme/static-road-network-data": [
    "https://w3id.org/mobilitydcat-ap/mobility-theme/geometry",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/gradients",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/junctions",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/number-of-lanes",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/road-classification",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/road-width",
  ],
  "https://w3id.org/mobilitydcat-ap/mobility-theme/static-traffic-signs-and-regulations": [
    "https://w3id.org/mobilitydcat-ap/mobility-theme/bridge-access-conditions",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/other-static-traffic-signs",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/other-traffic-regulations",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/permanent-access-restrictions",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/speed-limits",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/traffic-circulation-plans",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/tunnel-access-conditions",
  ],
  "https://w3id.org/mobilitydcat-ap/mobility-theme/toll-information": [
    "https://w3id.org/mobilitydcat-ap/mobility-theme/applicable-road-user-charges-and-payment-methods",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/identification-of-tolled-roads",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/location-of-tolling-stations",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/payment-methods-for-tolls",
  ],
  "https://w3id.org/mobilitydcat-ap/mobility-theme/waterways-and-water-bodies": [
  ],
} as const

export type TOP_MOBILITY_THEMES_T = keyof typeof MOBILITY_THEME_TREE
export type SUB_MOBILITY_THEMES_T = (typeof MOBILITY_THEME_TREE)[TOP_MOBILITY_THEMES_T][number]

export const TOP_MOBILITY_THEMES = new Set<TOP_MOBILITY_THEMES_T>(Object.keys(MOBILITY_THEME_TREE) as TOP_MOBILITY_THEMES_T[])
export const SUB_MOBILITY_THEMES = new Set<SUB_MOBILITY_THEMES_T>(Object.values(MOBILITY_THEME_TREE).flat() as SUB_MOBILITY_THEMES_T[])

export const MOBILITY_THEME_LABELS = {
  "https://w3id.org/mobilitydcat-ap/mobility-theme/accesibility-information-for-vehicles": "Accesibility information for vehicles",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/accidents-and-incidents": "Accidents and incidents",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/address-identifiers": "Address identifiers",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/air-and-space-travel": "Air and space travel",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/applicable-road-user-charges-and-payment-methods": "Applicable road user charges and payment methods",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/availability-of-charging-points-for-electric-vehicles": "Availability of charging points for electric vehicles",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/availability-of-delivery-areas": "Availability of delivery areas",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/availability-of-filling-stations": "Availability of filling stations",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/basic-commercial-conditions": "Basic commercial conditions",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/basic-common-standard-fares": "Basic common standard fares",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/bike-hiring-availability": "Bike-hiring Availability",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/bike-hiring-stations": "Bike-hiring Stations",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/bike-parking-locations": "Bike-parking locations",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/bike-sharing-availability": "Bike sharing Availability",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/bike-sharing-locations-and-stations": "Bike-sharing Locations and stations",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/bridge-access-conditions": "Bridge access conditions",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/bridge-closures-and-access-conditions": "Bridge closures and access conditions",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/car-hiring-availability": "Car-hiring Availability",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/car-hiring-stations": "Car-hiring Stations",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/car-parking-availability": "Car parking availability",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/car-parking-locations-and-conditions": "Car parking locations and conditions",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/car-sharing-availability": "Car-sharing Availability",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/car-sharing-locations-and-stations": "Car-sharing Locations and stations",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/common-fare-products": "Common fare products",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/connection-links": "Connection links",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/current-travel-times": "Current travel times",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/cycle-network-data": "Cycle network data",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/data-content-category": "Data content category",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/data-content-sub-category": "Data content sub-category",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/direction-of-travel-on-reversible-lanes": "Direction of travel on reversible lanes",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/disruptions-delays-cancellations": "Disruptions, delays, cancellations",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/dynamic-overtaking-bans-on-heavy-goods-vehicles": "Dynamic overtaking bans on heavy goods vehicles",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/dynamic-speed-limits": "Dynamic speed limits",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/dynamic-traffic-signs-and-regulations": "Dynamic traffic signs and regulations",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/e-scooter-sharing-availability": "E-scooter-sharing Availability",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/e-scooter-sharing-locations-and-stations": "E-scooter-sharing Locations and stations",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/environmental-standards-for-vehicles": "Environmental standards for vehicles",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/expected-delays": "Expected delays",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/fares": "Fares",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/filling-and-charging-stations": "Filling and charging stations",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/freight-and-logistics": "Freight and logistics",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/freight-delivery-regulations": "Freight delivery regulations",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/general-information-for-trip-planning-": "General information for trip-planning",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/geometry": "Geometry",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/gradients": "Gradients",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/hours-of-operation": "Hours of operation",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/identification-of-tolled-roads": "Identification of tolled roads",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/junctions": "Junctions",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/lane-closures-and-access-conditions": "Lane closures and access conditions",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/location-and-conditions-of-charging-points": "Location and conditions of charging points",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/location-and-conditions-of-filling-stations": "Location and conditions of filling stations",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/location-and-length-of-queues": "Location and length of queues",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/location-of-delivery-areas": "Location of delivery areas",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/location-of-tolling-stations": "Location of tolling stations",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/locations-and-stations": "Locations and stations",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/long-term-road-works": "Long-term road works",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/network-closures-diversions": "Network closures/diversions",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/network-detailed-attributes": "Network detailed attributes",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/network-geometry-and-lane-character": "Network geometry and lane character",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/network-topology-and-routes-lines": "Network topology and routes/lines",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/number-of-lanes": "Number of lanes",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/operational-calendar": "Operational Calendar",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/other": "Other",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/other-access-restrictions-and-traffic-regulations": "Other access restrictions and traffic regulations",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/other-static-traffic-signs": "Other static traffic signs",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/other-temporary-traffic-management-measures-or-plans": "Other temporary traffic management measures or plans",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/other-traffic-regulations": "Other traffic regulations",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/parameters-needed-to-calculate-costs": "Parameters needed to calculate costs",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/parameters-needed-to-calculate-environmental-factors": "Parameters needed to calculate environmental factors",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/park-and-ride-stops": "Park and Ride stops",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/parking-service-and-rest-area-information": "Parking, service and rest area information",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/passenger-classes": "Passenger classes",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/payment-methods": "Payment methods",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/payment-methods-for-tolls": "Payment methods for tolls",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/pedestrian-accessibility-facilities": "Pedestrian accessibility facilities",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/pedestrian-network-data": "Pedestrian network data",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/pedestrian-network-geometry": "Pedestrian network geometry",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/permanent-access-restrictions": "Permanent access restrictions",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/planned-interchanges-between-scheduled-services": "Planned interchanges between scheduled services",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/points-of-interest": "Points of interest",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/poor-road-conditions": "Poor road conditions",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/predicted-travel-times": "Predicted travel times",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/provider-data": "Provider data",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/public-transport-non-scheduled-transport": "Public transport non-scheduled transport",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/public-transport-scheduled-transport": "Public transport scheduled transport",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/purchase-information": "Purchase information",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/real-time-estimated-departure-and-arrival-times": "Real-time estimated departure and arrival times",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/real-time-traffic-data": "Real-time traffic data",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/reservation-and-purchase-options": "Reservation and purchase options",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/road-classification": "Road classification",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/road-closures-and-access-conditions": "Road closures and access conditions",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/road-events-and-conditions": "Road events and conditions",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/road-weather-conditions": "Road weather conditions",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/road-width": "Road width",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/road-work-information": "Road work information",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/service-and-rest-area-availability": "Service and rest area availability",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/service-and-rest-area-locations-and-conditions": "Service and rest area locations and conditions",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/service-areas-and-service-times": "Service areas and service times",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/sharing-and-hiring-services": "Sharing and Hiring Services",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/short-term-road-works": "Short-term road works",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/special-fare-products": "Special Fare Products",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/speed": "Speed",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/speed-limits": "Speed limits",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/static-road-network-data": "Static road network data",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/static-traffic-signs-and-regulations": "Static traffic signs and regulations",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/stop-facilities-accessibility-and-paths-within-facility": "Stop facilities accessibility and paths within facility",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/stop-facilities-geometry-and-map-layout": "Stop facilities geometry and map layout",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/stop-facilities-location-and-features": "Stop facilities location and features",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/stop-facilities-status-of-features": "Stop facilities status of features",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/timetables-static": "Timetables static",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/toll-information": "Toll information",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/topographic-places": "Topographic places",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/traffic-circulation-plans": "Traffic circulation plans",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/traffic-data-at-border-crossings-to-third-countries": "Traffic data at border crossings to third countries",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/traffic-volume": "Traffic volume",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/transport-operators": "Transport operators",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/truck-parking-availability": "Truck parking availability",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/truck-parking-locations-and-conditions": "Truck parking locations and conditions",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/tunnel-access-conditions": "Tunnel access conditions",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/tunnel-closures-and-access-conditions": "Tunnel closures and access conditions",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/vehicle-details": "Vehicle details",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/waiting-time-at-border-crossings-to-non-eu-member-states": "Waiting time at border crossings to non-EU Member States",
  "https://w3id.org/mobilitydcat-ap/mobility-theme/waterways-and-water-bodies": "Waterways and water bodies",
}

export function isTopMobilityTheme(obj: unknown): obj is TOP_MOBILITY_THEMES_T {
  return typeof obj === 'string' && TOP_MOBILITY_THEMES.has(obj)
}

export function isSubMobilityTheme(obj: unknown): obj is SUB_MOBILITY_THEMES_T {
  return typeof obj === 'string' && SUB_MOBILITY_THEMES.has(obj)
}