import {getObjectKeyByValue} from "../util";

export enum RegionalCoverage {
  NUTS_FI = "http://data.europa.eu/nuts/code/FI",
  NUTS_FI1 = "http://data.europa.eu/nuts/code/FI1",
  NUTS_FI19 = "http://data.europa.eu/nuts/code/FI19",
  NUTS_FI196 = "http://data.europa.eu/nuts/code/FI196",
  NUTS_FI198 = "http://data.europa.eu/nuts/code/FI198",
  NUTS_FI199 = "http://data.europa.eu/nuts/code/FI199",
  NUTS_FI19A = "http://data.europa.eu/nuts/code/FI19A",
  NUTS_FI19B = "http://data.europa.eu/nuts/code/FI19B",
  NUTS_FI1B = "http://data.europa.eu/nuts/code/FI1B",
  NUTS_FI1B1 = "http://data.europa.eu/nuts/code/FI1B1",
  NUTS_FI1C = "http://data.europa.eu/nuts/code/FI1C",
  NUTS_FI1C1 = "http://data.europa.eu/nuts/code/FI1C1",
  NUTS_FI1C2 = "http://data.europa.eu/nuts/code/FI1C2",
  NUTS_FI1C5 = "http://data.europa.eu/nuts/code/FI1C5",
  NUTS_FI1C6 = "http://data.europa.eu/nuts/code/FI1C6",
  NUTS_FI1C7 = "http://data.europa.eu/nuts/code/FI1C7",
  NUTS_FI1D = "http://data.europa.eu/nuts/code/FI1D",
  NUTS_FI1D5 = "http://data.europa.eu/nuts/code/FI1D5",
  NUTS_FI1D7 = "http://data.europa.eu/nuts/code/FI1D7",
  NUTS_FI1D8 = "http://data.europa.eu/nuts/code/FI1D8",
  NUTS_FI1D9 = "http://data.europa.eu/nuts/code/FI1D9",
  NUTS_FI1DA = "http://data.europa.eu/nuts/code/FI1DA",
  NUTS_FI1DB = "http://data.europa.eu/nuts/code/FI1DB",
  NUTS_FI1DC = "http://data.europa.eu/nuts/code/FI1DC",
  NUTS_FI2 = "http://data.europa.eu/nuts/code/FI2",
  NUTS_FI20 = "http://data.europa.eu/nuts/code/FI20",
  NUTS_FI200 = "http://data.europa.eu/nuts/code/FI200",
  NUTS_FIZ = "http://data.europa.eu/nuts/code/FIZ",
  NUTS_FIZZ = "http://data.europa.eu/nuts/code/FIZZ",
  NUTS_FIZZZ = "http://data.europa.eu/nuts/code/FIZZZ",
  LAU_FI_020 = "https://w3id.org/stirdata/resource/lau/item/FI_020",
  LAU_FI_005 = "https://w3id.org/stirdata/resource/lau/item/FI_005",
  LAU_FI_009 = "https://w3id.org/stirdata/resource/lau/item/FI_009",
  LAU_FI_010 = "https://w3id.org/stirdata/resource/lau/item/FI_010",
  LAU_FI_016 = "https://w3id.org/stirdata/resource/lau/item/FI_016",
  LAU_FI_018 = "https://w3id.org/stirdata/resource/lau/item/FI_018",
  LAU_FI_019 = "https://w3id.org/stirdata/resource/lau/item/FI_019",
  LAU_FI_035 = "https://w3id.org/stirdata/resource/lau/item/FI_035",
  LAU_FI_043 = "https://w3id.org/stirdata/resource/lau/item/FI_043",
  LAU_FI_046 = "https://w3id.org/stirdata/resource/lau/item/FI_046",
  LAU_FI_047 = "https://w3id.org/stirdata/resource/lau/item/FI_047",
  LAU_FI_049 = "https://w3id.org/stirdata/resource/lau/item/FI_049",
  LAU_FI_050 = "https://w3id.org/stirdata/resource/lau/item/FI_050",
  LAU_FI_051 = "https://w3id.org/stirdata/resource/lau/item/FI_051",
  LAU_FI_052 = "https://w3id.org/stirdata/resource/lau/item/FI_052",
  LAU_FI_060 = "https://w3id.org/stirdata/resource/lau/item/FI_060",
  LAU_FI_061 = "https://w3id.org/stirdata/resource/lau/item/FI_061",
  LAU_FI_062 = "https://w3id.org/stirdata/resource/lau/item/FI_062",
  LAU_FI_065 = "https://w3id.org/stirdata/resource/lau/item/FI_065",
  LAU_FI_069 = "https://w3id.org/stirdata/resource/lau/item/FI_069",
  LAU_FI_071 = "https://w3id.org/stirdata/resource/lau/item/FI_071",
  LAU_FI_072 = "https://w3id.org/stirdata/resource/lau/item/FI_072",
  LAU_FI_074 = "https://w3id.org/stirdata/resource/lau/item/FI_074",
  LAU_FI_075 = "https://w3id.org/stirdata/resource/lau/item/FI_075",
  LAU_FI_076 = "https://w3id.org/stirdata/resource/lau/item/FI_076",
  LAU_FI_077 = "https://w3id.org/stirdata/resource/lau/item/FI_077",
  LAU_FI_078 = "https://w3id.org/stirdata/resource/lau/item/FI_078",
  LAU_FI_079 = "https://w3id.org/stirdata/resource/lau/item/FI_079",
  LAU_FI_081 = "https://w3id.org/stirdata/resource/lau/item/FI_081",
  LAU_FI_082 = "https://w3id.org/stirdata/resource/lau/item/FI_082",
  LAU_FI_086 = "https://w3id.org/stirdata/resource/lau/item/FI_086",
  LAU_FI_111 = "https://w3id.org/stirdata/resource/lau/item/FI_111",
  LAU_FI_090 = "https://w3id.org/stirdata/resource/lau/item/FI_090",
  LAU_FI_091 = "https://w3id.org/stirdata/resource/lau/item/FI_091",
  LAU_FI_097 = "https://w3id.org/stirdata/resource/lau/item/FI_097",
  LAU_FI_098 = "https://w3id.org/stirdata/resource/lau/item/FI_098",
  LAU_FI_099 = "https://w3id.org/stirdata/resource/lau/item/FI_099",
  LAU_FI_102 = "https://w3id.org/stirdata/resource/lau/item/FI_102",
  LAU_FI_103 = "https://w3id.org/stirdata/resource/lau/item/FI_103",
  LAU_FI_105 = "https://w3id.org/stirdata/resource/lau/item/FI_105",
  LAU_FI_106 = "https://w3id.org/stirdata/resource/lau/item/FI_106",
  LAU_FI_108 = "https://w3id.org/stirdata/resource/lau/item/FI_108",
  LAU_FI_109 = "https://w3id.org/stirdata/resource/lau/item/FI_109",
  LAU_FI_139 = "https://w3id.org/stirdata/resource/lau/item/FI_139",
  LAU_FI_140 = "https://w3id.org/stirdata/resource/lau/item/FI_140",
  LAU_FI_142 = "https://w3id.org/stirdata/resource/lau/item/FI_142",
  LAU_FI_143 = "https://w3id.org/stirdata/resource/lau/item/FI_143",
  LAU_FI_145 = "https://w3id.org/stirdata/resource/lau/item/FI_145",
  LAU_FI_146 = "https://w3id.org/stirdata/resource/lau/item/FI_146",
  LAU_FI_153 = "https://w3id.org/stirdata/resource/lau/item/FI_153",
  LAU_FI_148 = "https://w3id.org/stirdata/resource/lau/item/FI_148",
  LAU_FI_149 = "https://w3id.org/stirdata/resource/lau/item/FI_149",
  LAU_FI_151 = "https://w3id.org/stirdata/resource/lau/item/FI_151",
  LAU_FI_152 = "https://w3id.org/stirdata/resource/lau/item/FI_152",
  LAU_FI_165 = "https://w3id.org/stirdata/resource/lau/item/FI_165",
  LAU_FI_167 = "https://w3id.org/stirdata/resource/lau/item/FI_167",
  LAU_FI_169 = "https://w3id.org/stirdata/resource/lau/item/FI_169",
  LAU_FI_170 = "https://w3id.org/stirdata/resource/lau/item/FI_170",
  LAU_FI_171 = "https://w3id.org/stirdata/resource/lau/item/FI_171",
  LAU_FI_172 = "https://w3id.org/stirdata/resource/lau/item/FI_172",
  LAU_FI_176 = "https://w3id.org/stirdata/resource/lau/item/FI_176",
  LAU_FI_177 = "https://w3id.org/stirdata/resource/lau/item/FI_177",
  LAU_FI_178 = "https://w3id.org/stirdata/resource/lau/item/FI_178",
  LAU_FI_179 = "https://w3id.org/stirdata/resource/lau/item/FI_179",
  LAU_FI_181 = "https://w3id.org/stirdata/resource/lau/item/FI_181",
  LAU_FI_182 = "https://w3id.org/stirdata/resource/lau/item/FI_182",
  LAU_FI_186 = "https://w3id.org/stirdata/resource/lau/item/FI_186",
  LAU_FI_202 = "https://w3id.org/stirdata/resource/lau/item/FI_202",
  LAU_FI_204 = "https://w3id.org/stirdata/resource/lau/item/FI_204",
  LAU_FI_205 = "https://w3id.org/stirdata/resource/lau/item/FI_205",
  LAU_FI_208 = "https://w3id.org/stirdata/resource/lau/item/FI_208",
  LAU_FI_211 = "https://w3id.org/stirdata/resource/lau/item/FI_211",
  LAU_FI_213 = "https://w3id.org/stirdata/resource/lau/item/FI_213",
  LAU_FI_214 = "https://w3id.org/stirdata/resource/lau/item/FI_214",
  LAU_FI_216 = "https://w3id.org/stirdata/resource/lau/item/FI_216",
  LAU_FI_217 = "https://w3id.org/stirdata/resource/lau/item/FI_217",
  LAU_FI_218 = "https://w3id.org/stirdata/resource/lau/item/FI_218",
  LAU_FI_224 = "https://w3id.org/stirdata/resource/lau/item/FI_224",
  LAU_FI_226 = "https://w3id.org/stirdata/resource/lau/item/FI_226",
  LAU_FI_230 = "https://w3id.org/stirdata/resource/lau/item/FI_230",
  LAU_FI_231 = "https://w3id.org/stirdata/resource/lau/item/FI_231",
  LAU_FI_232 = "https://w3id.org/stirdata/resource/lau/item/FI_232",
  LAU_FI_233 = "https://w3id.org/stirdata/resource/lau/item/FI_233",
  LAU_FI_235 = "https://w3id.org/stirdata/resource/lau/item/FI_235",
  LAU_FI_236 = "https://w3id.org/stirdata/resource/lau/item/FI_236",
  LAU_FI_239 = "https://w3id.org/stirdata/resource/lau/item/FI_239",
  LAU_FI_240 = "https://w3id.org/stirdata/resource/lau/item/FI_240",
  LAU_FI_320 = "https://w3id.org/stirdata/resource/lau/item/FI_320",
  LAU_FI_241 = "https://w3id.org/stirdata/resource/lau/item/FI_241",
  LAU_FI_322 = "https://w3id.org/stirdata/resource/lau/item/FI_322",
  LAU_FI_244 = "https://w3id.org/stirdata/resource/lau/item/FI_244",
  LAU_FI_245 = "https://w3id.org/stirdata/resource/lau/item/FI_245",
  LAU_FI_249 = "https://w3id.org/stirdata/resource/lau/item/FI_249",
  LAU_FI_250 = "https://w3id.org/stirdata/resource/lau/item/FI_250",
  LAU_FI_256 = "https://w3id.org/stirdata/resource/lau/item/FI_256",
  LAU_FI_257 = "https://w3id.org/stirdata/resource/lau/item/FI_257",
  LAU_FI_260 = "https://w3id.org/stirdata/resource/lau/item/FI_260",
  LAU_FI_261 = "https://w3id.org/stirdata/resource/lau/item/FI_261",
  LAU_FI_263 = "https://w3id.org/stirdata/resource/lau/item/FI_263",
  LAU_FI_265 = "https://w3id.org/stirdata/resource/lau/item/FI_265",
  LAU_FI_271 = "https://w3id.org/stirdata/resource/lau/item/FI_271",
  LAU_FI_272 = "https://w3id.org/stirdata/resource/lau/item/FI_272",
  LAU_FI_273 = "https://w3id.org/stirdata/resource/lau/item/FI_273",
  LAU_FI_275 = "https://w3id.org/stirdata/resource/lau/item/FI_275",
  LAU_FI_276 = "https://w3id.org/stirdata/resource/lau/item/FI_276",
  LAU_FI_280 = "https://w3id.org/stirdata/resource/lau/item/FI_280",
  LAU_FI_284 = "https://w3id.org/stirdata/resource/lau/item/FI_284",
  LAU_FI_285 = "https://w3id.org/stirdata/resource/lau/item/FI_285",
  LAU_FI_286 = "https://w3id.org/stirdata/resource/lau/item/FI_286",
  LAU_FI_287 = "https://w3id.org/stirdata/resource/lau/item/FI_287",
  LAU_FI_288 = "https://w3id.org/stirdata/resource/lau/item/FI_288",
  LAU_FI_290 = "https://w3id.org/stirdata/resource/lau/item/FI_290",
  LAU_FI_291 = "https://w3id.org/stirdata/resource/lau/item/FI_291",
  LAU_FI_295 = "https://w3id.org/stirdata/resource/lau/item/FI_295",
  LAU_FI_297 = "https://w3id.org/stirdata/resource/lau/item/FI_297",
  LAU_FI_300 = "https://w3id.org/stirdata/resource/lau/item/FI_300",
  LAU_FI_301 = "https://w3id.org/stirdata/resource/lau/item/FI_301",
  LAU_FI_304 = "https://w3id.org/stirdata/resource/lau/item/FI_304",
  LAU_FI_305 = "https://w3id.org/stirdata/resource/lau/item/FI_305",
  LAU_FI_312 = "https://w3id.org/stirdata/resource/lau/item/FI_312",
  LAU_FI_316 = "https://w3id.org/stirdata/resource/lau/item/FI_316",
  LAU_FI_317 = "https://w3id.org/stirdata/resource/lau/item/FI_317",
  LAU_FI_318 = "https://w3id.org/stirdata/resource/lau/item/FI_318",
  LAU_FI_398 = "https://w3id.org/stirdata/resource/lau/item/FI_398",
  LAU_FI_399 = "https://w3id.org/stirdata/resource/lau/item/FI_399",
  LAU_FI_400 = "https://w3id.org/stirdata/resource/lau/item/FI_400",
  LAU_FI_407 = "https://w3id.org/stirdata/resource/lau/item/FI_407",
  LAU_FI_402 = "https://w3id.org/stirdata/resource/lau/item/FI_402",
  LAU_FI_403 = "https://w3id.org/stirdata/resource/lau/item/FI_403",
  LAU_FI_405 = "https://w3id.org/stirdata/resource/lau/item/FI_405",
  LAU_FI_408 = "https://w3id.org/stirdata/resource/lau/item/FI_408",
  LAU_FI_410 = "https://w3id.org/stirdata/resource/lau/item/FI_410",
  LAU_FI_416 = "https://w3id.org/stirdata/resource/lau/item/FI_416",
  LAU_FI_417 = "https://w3id.org/stirdata/resource/lau/item/FI_417",
  LAU_FI_418 = "https://w3id.org/stirdata/resource/lau/item/FI_418",
  LAU_FI_420 = "https://w3id.org/stirdata/resource/lau/item/FI_420",
  LAU_FI_421 = "https://w3id.org/stirdata/resource/lau/item/FI_421",
  LAU_FI_422 = "https://w3id.org/stirdata/resource/lau/item/FI_422",
  LAU_FI_423 = "https://w3id.org/stirdata/resource/lau/item/FI_423",
  LAU_FI_425 = "https://w3id.org/stirdata/resource/lau/item/FI_425",
  LAU_FI_426 = "https://w3id.org/stirdata/resource/lau/item/FI_426",
  LAU_FI_444 = "https://w3id.org/stirdata/resource/lau/item/FI_444",
  LAU_FI_430 = "https://w3id.org/stirdata/resource/lau/item/FI_430",
  LAU_FI_433 = "https://w3id.org/stirdata/resource/lau/item/FI_433",
  LAU_FI_434 = "https://w3id.org/stirdata/resource/lau/item/FI_434",
  LAU_FI_435 = "https://w3id.org/stirdata/resource/lau/item/FI_435",
  LAU_FI_436 = "https://w3id.org/stirdata/resource/lau/item/FI_436",
  LAU_FI_438 = "https://w3id.org/stirdata/resource/lau/item/FI_438",
  LAU_FI_440 = "https://w3id.org/stirdata/resource/lau/item/FI_440",
  LAU_FI_441 = "https://w3id.org/stirdata/resource/lau/item/FI_441",
  LAU_FI_475 = "https://w3id.org/stirdata/resource/lau/item/FI_475",
  LAU_FI_478 = "https://w3id.org/stirdata/resource/lau/item/FI_478",
  LAU_FI_480 = "https://w3id.org/stirdata/resource/lau/item/FI_480",
  LAU_FI_481 = "https://w3id.org/stirdata/resource/lau/item/FI_481",
  LAU_FI_483 = "https://w3id.org/stirdata/resource/lau/item/FI_483",
  LAU_FI_484 = "https://w3id.org/stirdata/resource/lau/item/FI_484",
  LAU_FI_489 = "https://w3id.org/stirdata/resource/lau/item/FI_489",
  LAU_FI_491 = "https://w3id.org/stirdata/resource/lau/item/FI_491",
  LAU_FI_494 = "https://w3id.org/stirdata/resource/lau/item/FI_494",
  LAU_FI_495 = "https://w3id.org/stirdata/resource/lau/item/FI_495",
  LAU_FI_498 = "https://w3id.org/stirdata/resource/lau/item/FI_498",
  LAU_FI_499 = "https://w3id.org/stirdata/resource/lau/item/FI_499",
  LAU_FI_500 = "https://w3id.org/stirdata/resource/lau/item/FI_500",
  LAU_FI_503 = "https://w3id.org/stirdata/resource/lau/item/FI_503",
  LAU_FI_504 = "https://w3id.org/stirdata/resource/lau/item/FI_504",
  LAU_FI_505 = "https://w3id.org/stirdata/resource/lau/item/FI_505",
  LAU_FI_508 = "https://w3id.org/stirdata/resource/lau/item/FI_508",
  LAU_FI_507 = "https://w3id.org/stirdata/resource/lau/item/FI_507",
  LAU_FI_529 = "https://w3id.org/stirdata/resource/lau/item/FI_529",
  LAU_FI_531 = "https://w3id.org/stirdata/resource/lau/item/FI_531",
  LAU_FI_535 = "https://w3id.org/stirdata/resource/lau/item/FI_535",
  LAU_FI_536 = "https://w3id.org/stirdata/resource/lau/item/FI_536",
  LAU_FI_538 = "https://w3id.org/stirdata/resource/lau/item/FI_538",
  LAU_FI_541 = "https://w3id.org/stirdata/resource/lau/item/FI_541",
  LAU_FI_543 = "https://w3id.org/stirdata/resource/lau/item/FI_543",
  LAU_FI_545 = "https://w3id.org/stirdata/resource/lau/item/FI_545",
  LAU_FI_560 = "https://w3id.org/stirdata/resource/lau/item/FI_560",
  LAU_FI_561 = "https://w3id.org/stirdata/resource/lau/item/FI_561",
  LAU_FI_562 = "https://w3id.org/stirdata/resource/lau/item/FI_562",
  LAU_FI_563 = "https://w3id.org/stirdata/resource/lau/item/FI_563",
  LAU_FI_564 = "https://w3id.org/stirdata/resource/lau/item/FI_564",
  LAU_FI_309 = "https://w3id.org/stirdata/resource/lau/item/FI_309",
  LAU_FI_576 = "https://w3id.org/stirdata/resource/lau/item/FI_576",
  LAU_FI_577 = "https://w3id.org/stirdata/resource/lau/item/FI_577",
  LAU_FI_578 = "https://w3id.org/stirdata/resource/lau/item/FI_578",
  LAU_FI_445 = "https://w3id.org/stirdata/resource/lau/item/FI_445",
  LAU_FI_580 = "https://w3id.org/stirdata/resource/lau/item/FI_580",
  LAU_FI_581 = "https://w3id.org/stirdata/resource/lau/item/FI_581",
  LAU_FI_599 = "https://w3id.org/stirdata/resource/lau/item/FI_599",
  LAU_FI_583 = "https://w3id.org/stirdata/resource/lau/item/FI_583",
  LAU_FI_854 = "https://w3id.org/stirdata/resource/lau/item/FI_854",
  LAU_FI_584 = "https://w3id.org/stirdata/resource/lau/item/FI_584",
  LAU_FI_588 = "https://w3id.org/stirdata/resource/lau/item/FI_588",
  LAU_FI_592 = "https://w3id.org/stirdata/resource/lau/item/FI_592",
  LAU_FI_593 = "https://w3id.org/stirdata/resource/lau/item/FI_593",
  LAU_FI_595 = "https://w3id.org/stirdata/resource/lau/item/FI_595",
  LAU_FI_598 = "https://w3id.org/stirdata/resource/lau/item/FI_598",
  LAU_FI_601 = "https://w3id.org/stirdata/resource/lau/item/FI_601",
  LAU_FI_604 = "https://w3id.org/stirdata/resource/lau/item/FI_604",
  LAU_FI_607 = "https://w3id.org/stirdata/resource/lau/item/FI_607",
  LAU_FI_608 = "https://w3id.org/stirdata/resource/lau/item/FI_608",
  LAU_FI_609 = "https://w3id.org/stirdata/resource/lau/item/FI_609",
  LAU_FI_611 = "https://w3id.org/stirdata/resource/lau/item/FI_611",
  LAU_FI_638 = "https://w3id.org/stirdata/resource/lau/item/FI_638",
  LAU_FI_614 = "https://w3id.org/stirdata/resource/lau/item/FI_614",
  LAU_FI_615 = "https://w3id.org/stirdata/resource/lau/item/FI_615",
  LAU_FI_616 = "https://w3id.org/stirdata/resource/lau/item/FI_616",
  LAU_FI_619 = "https://w3id.org/stirdata/resource/lau/item/FI_619",
  LAU_FI_620 = "https://w3id.org/stirdata/resource/lau/item/FI_620",
  LAU_FI_623 = "https://w3id.org/stirdata/resource/lau/item/FI_623",
  LAU_FI_624 = "https://w3id.org/stirdata/resource/lau/item/FI_624",
  LAU_FI_625 = "https://w3id.org/stirdata/resource/lau/item/FI_625",
  LAU_FI_626 = "https://w3id.org/stirdata/resource/lau/item/FI_626",
  LAU_FI_630 = "https://w3id.org/stirdata/resource/lau/item/FI_630",
  LAU_FI_631 = "https://w3id.org/stirdata/resource/lau/item/FI_631",
  LAU_FI_635 = "https://w3id.org/stirdata/resource/lau/item/FI_635",
  LAU_FI_636 = "https://w3id.org/stirdata/resource/lau/item/FI_636",
  LAU_FI_678 = "https://w3id.org/stirdata/resource/lau/item/FI_678",
  LAU_FI_710 = "https://w3id.org/stirdata/resource/lau/item/FI_710",
  LAU_FI_680 = "https://w3id.org/stirdata/resource/lau/item/FI_680",
  LAU_FI_681 = "https://w3id.org/stirdata/resource/lau/item/FI_681",
  LAU_FI_683 = "https://w3id.org/stirdata/resource/lau/item/FI_683",
  LAU_FI_684 = "https://w3id.org/stirdata/resource/lau/item/FI_684",
  LAU_FI_686 = "https://w3id.org/stirdata/resource/lau/item/FI_686",
  LAU_FI_687 = "https://w3id.org/stirdata/resource/lau/item/FI_687",
  LAU_FI_689 = "https://w3id.org/stirdata/resource/lau/item/FI_689",
  LAU_FI_691 = "https://w3id.org/stirdata/resource/lau/item/FI_691",
  LAU_FI_694 = "https://w3id.org/stirdata/resource/lau/item/FI_694",
  LAU_FI_697 = "https://w3id.org/stirdata/resource/lau/item/FI_697",
  LAU_FI_698 = "https://w3id.org/stirdata/resource/lau/item/FI_698",
  LAU_FI_700 = "https://w3id.org/stirdata/resource/lau/item/FI_700",
  LAU_FI_702 = "https://w3id.org/stirdata/resource/lau/item/FI_702",
  LAU_FI_704 = "https://w3id.org/stirdata/resource/lau/item/FI_704",
  LAU_FI_707 = "https://w3id.org/stirdata/resource/lau/item/FI_707",
  LAU_FI_729 = "https://w3id.org/stirdata/resource/lau/item/FI_729",
  LAU_FI_732 = "https://w3id.org/stirdata/resource/lau/item/FI_732",
  LAU_FI_734 = "https://w3id.org/stirdata/resource/lau/item/FI_734",
  LAU_FI_736 = "https://w3id.org/stirdata/resource/lau/item/FI_736",
  LAU_FI_790 = "https://w3id.org/stirdata/resource/lau/item/FI_790",
  LAU_FI_738 = "https://w3id.org/stirdata/resource/lau/item/FI_738",
  LAU_FI_739 = "https://w3id.org/stirdata/resource/lau/item/FI_739",
  LAU_FI_740 = "https://w3id.org/stirdata/resource/lau/item/FI_740",
  LAU_FI_742 = "https://w3id.org/stirdata/resource/lau/item/FI_742",
  LAU_FI_743 = "https://w3id.org/stirdata/resource/lau/item/FI_743",
  LAU_FI_746 = "https://w3id.org/stirdata/resource/lau/item/FI_746",
  LAU_FI_747 = "https://w3id.org/stirdata/resource/lau/item/FI_747",
  LAU_FI_748 = "https://w3id.org/stirdata/resource/lau/item/FI_748",
  LAU_FI_791 = "https://w3id.org/stirdata/resource/lau/item/FI_791",
  LAU_FI_749 = "https://w3id.org/stirdata/resource/lau/item/FI_749",
  LAU_FI_751 = "https://w3id.org/stirdata/resource/lau/item/FI_751",
  LAU_FI_753 = "https://w3id.org/stirdata/resource/lau/item/FI_753",
  LAU_FI_755 = "https://w3id.org/stirdata/resource/lau/item/FI_755",
  LAU_FI_758 = "https://w3id.org/stirdata/resource/lau/item/FI_758",
  LAU_FI_759 = "https://w3id.org/stirdata/resource/lau/item/FI_759",
  LAU_FI_761 = "https://w3id.org/stirdata/resource/lau/item/FI_761",
  LAU_FI_762 = "https://w3id.org/stirdata/resource/lau/item/FI_762",
  LAU_FI_765 = "https://w3id.org/stirdata/resource/lau/item/FI_765",
  LAU_FI_766 = "https://w3id.org/stirdata/resource/lau/item/FI_766",
  LAU_FI_768 = "https://w3id.org/stirdata/resource/lau/item/FI_768",
  LAU_FI_771 = "https://w3id.org/stirdata/resource/lau/item/FI_771",
  LAU_FI_777 = "https://w3id.org/stirdata/resource/lau/item/FI_777",
  LAU_FI_778 = "https://w3id.org/stirdata/resource/lau/item/FI_778",
  LAU_FI_781 = "https://w3id.org/stirdata/resource/lau/item/FI_781",
  LAU_FI_783 = "https://w3id.org/stirdata/resource/lau/item/FI_783",
  LAU_FI_831 = "https://w3id.org/stirdata/resource/lau/item/FI_831",
  LAU_FI_832 = "https://w3id.org/stirdata/resource/lau/item/FI_832",
  LAU_FI_833 = "https://w3id.org/stirdata/resource/lau/item/FI_833",
  LAU_FI_834 = "https://w3id.org/stirdata/resource/lau/item/FI_834",
  LAU_FI_837 = "https://w3id.org/stirdata/resource/lau/item/FI_837",
  LAU_FI_844 = "https://w3id.org/stirdata/resource/lau/item/FI_844",
  LAU_FI_845 = "https://w3id.org/stirdata/resource/lau/item/FI_845",
  LAU_FI_846 = "https://w3id.org/stirdata/resource/lau/item/FI_846",
  LAU_FI_848 = "https://w3id.org/stirdata/resource/lau/item/FI_848",
  LAU_FI_849 = "https://w3id.org/stirdata/resource/lau/item/FI_849",
  LAU_FI_850 = "https://w3id.org/stirdata/resource/lau/item/FI_850",
  LAU_FI_851 = "https://w3id.org/stirdata/resource/lau/item/FI_851",
  LAU_FI_853 = "https://w3id.org/stirdata/resource/lau/item/FI_853",
  LAU_FI_857 = "https://w3id.org/stirdata/resource/lau/item/FI_857",
  LAU_FI_858 = "https://w3id.org/stirdata/resource/lau/item/FI_858",
  LAU_FI_859 = "https://w3id.org/stirdata/resource/lau/item/FI_859",
  LAU_FI_886 = "https://w3id.org/stirdata/resource/lau/item/FI_886",
  LAU_FI_887 = "https://w3id.org/stirdata/resource/lau/item/FI_887",
  LAU_FI_889 = "https://w3id.org/stirdata/resource/lau/item/FI_889",
  LAU_FI_890 = "https://w3id.org/stirdata/resource/lau/item/FI_890",
  LAU_FI_892 = "https://w3id.org/stirdata/resource/lau/item/FI_892",
  LAU_FI_893 = "https://w3id.org/stirdata/resource/lau/item/FI_893",
  LAU_FI_895 = "https://w3id.org/stirdata/resource/lau/item/FI_895",
  LAU_FI_785 = "https://w3id.org/stirdata/resource/lau/item/FI_785",
  LAU_FI_905 = "https://w3id.org/stirdata/resource/lau/item/FI_905",
  LAU_FI_908 = "https://w3id.org/stirdata/resource/lau/item/FI_908",
  LAU_FI_092 = "https://w3id.org/stirdata/resource/lau/item/FI_092",
  LAU_FI_915 = "https://w3id.org/stirdata/resource/lau/item/FI_915",
  LAU_FI_918 = "https://w3id.org/stirdata/resource/lau/item/FI_918",
  LAU_FI_921 = "https://w3id.org/stirdata/resource/lau/item/FI_921",
  LAU_FI_922 = "https://w3id.org/stirdata/resource/lau/item/FI_922",
  LAU_FI_924 = "https://w3id.org/stirdata/resource/lau/item/FI_924",
  LAU_FI_925 = "https://w3id.org/stirdata/resource/lau/item/FI_925",
  LAU_FI_927 = "https://w3id.org/stirdata/resource/lau/item/FI_927",
  LAU_FI_931 = "https://w3id.org/stirdata/resource/lau/item/FI_931",
  LAU_FI_934 = "https://w3id.org/stirdata/resource/lau/item/FI_934",
  LAU_FI_935 = "https://w3id.org/stirdata/resource/lau/item/FI_935",
  LAU_FI_936 = "https://w3id.org/stirdata/resource/lau/item/FI_936",
  LAU_FI_941 = "https://w3id.org/stirdata/resource/lau/item/FI_941",
  LAU_FI_946 = "https://w3id.org/stirdata/resource/lau/item/FI_946",
  LAU_FI_976 = "https://w3id.org/stirdata/resource/lau/item/FI_976",
  LAU_FI_977 = "https://w3id.org/stirdata/resource/lau/item/FI_977",
  LAU_FI_980 = "https://w3id.org/stirdata/resource/lau/item/FI_980",
  LAU_FI_981 = "https://w3id.org/stirdata/resource/lau/item/FI_981",
  LAU_FI_989 = "https://w3id.org/stirdata/resource/lau/item/FI_989",
  LAU_FI_992 = "https://w3id.org/stirdata/resource/lau/item/FI_992",
}

export const regionalCoverageLabels: Record<RegionalCoverage, string> = {
  [RegionalCoverage.NUTS_FI]: 'FI Suomi/Finland',
  [RegionalCoverage.NUTS_FI1]: 'FI1 Manner-Suomi',
  [RegionalCoverage.NUTS_FI19]: 'FI19 Länsi-Suomi',
  [RegionalCoverage.NUTS_FI196]: 'FI196 Satakunta',
  [RegionalCoverage.NUTS_FI198]: 'FI198 Keski-Suomi',
  [RegionalCoverage.NUTS_FI199]: 'FI199 Etelä-Pohjanmaa',
  [RegionalCoverage.NUTS_FI19A]: 'FI19A Pohjanmaa',
  [RegionalCoverage.NUTS_FI19B]: 'FI19B Pirkanmaa',
  [RegionalCoverage.NUTS_FI1B]: 'FI1B Helsinki-Uusimaa',
  [RegionalCoverage.NUTS_FI1B1]: 'FI1B1 Helsinki-Uusimaa',
  [RegionalCoverage.NUTS_FI1C]: 'FI1C Etelä-Suomi',
  [RegionalCoverage.NUTS_FI1C1]: 'FI1C1 Varsinais-Suomi',
  [RegionalCoverage.NUTS_FI1C2]: 'FI1C2 Kanta-Häme',
  [RegionalCoverage.NUTS_FI1C5]: 'FI1C5 Etelä-Karjala',
  [RegionalCoverage.NUTS_FI1C6]: 'FI1C6 Päijät-Häme',
  [RegionalCoverage.NUTS_FI1C7]: 'FI1C7 Kymenlaakso',
  [RegionalCoverage.NUTS_FI1D]: 'FI1D Pohjois- ja Itä-Suomi',
  [RegionalCoverage.NUTS_FI1D5]: 'FI1D5 Keski-Pohjanmaa',
  [RegionalCoverage.NUTS_FI1D7]: 'FI1D7 Lappi',
  [RegionalCoverage.NUTS_FI1D8]: 'FI1D8 Kainuu',
  [RegionalCoverage.NUTS_FI1D9]: 'FI1D9 Pohjois-Pohjanmaa',
  [RegionalCoverage.NUTS_FI1DA]: 'FI1DA Etelä-Savo',
  [RegionalCoverage.NUTS_FI1DB]: 'FI1DB Pohjois-Savo',
  [RegionalCoverage.NUTS_FI1DC]: 'FI1DC Pohjois-Karjala',
  [RegionalCoverage.NUTS_FI2]: 'FI2 Åland',
  [RegionalCoverage.NUTS_FI20]: 'FI20 Åland',
  [RegionalCoverage.NUTS_FI200]: 'FI200 Åland',
  [RegionalCoverage.NUTS_FIZ]: 'FIZ Extra-Regio NUTS 1',
  [RegionalCoverage.NUTS_FIZZ]: 'FIZZ Extra-Regio NUTS 2',
  [RegionalCoverage.NUTS_FIZZZ]: 'FIZZZ Extra-Regio NUTS 3',
  [RegionalCoverage.LAU_FI_020]: 'Akaa',
  [RegionalCoverage.LAU_FI_005]: 'Alajärvi',
  [RegionalCoverage.LAU_FI_009]: 'Alavieska',
  [RegionalCoverage.LAU_FI_010]: 'Alavus',
  [RegionalCoverage.LAU_FI_016]: 'Asikkala',
  [RegionalCoverage.LAU_FI_018]: 'Askola',
  [RegionalCoverage.LAU_FI_019]: 'Aura',
  [RegionalCoverage.LAU_FI_035]: 'Brändö',
  [RegionalCoverage.LAU_FI_043]: 'Eckerö',
  [RegionalCoverage.LAU_FI_046]: 'Enonkoski',
  [RegionalCoverage.LAU_FI_047]: 'Enontekiö',
  [RegionalCoverage.LAU_FI_049]: 'Espoo',
  [RegionalCoverage.LAU_FI_050]: 'Eura',
  [RegionalCoverage.LAU_FI_051]: 'Eurajoki',
  [RegionalCoverage.LAU_FI_052]: 'Evijärvi',
  [RegionalCoverage.LAU_FI_060]: 'Finström',
  [RegionalCoverage.LAU_FI_061]: 'Forssa',
  [RegionalCoverage.LAU_FI_062]: 'Föglö',
  [RegionalCoverage.LAU_FI_065]: 'Geta',
  [RegionalCoverage.LAU_FI_069]: 'Haapajärvi',
  [RegionalCoverage.LAU_FI_071]: 'Haapavesi',
  [RegionalCoverage.LAU_FI_072]: 'Hailuoto',
  [RegionalCoverage.LAU_FI_074]: 'Halsua',
  [RegionalCoverage.LAU_FI_075]: 'Hamina',
  [RegionalCoverage.LAU_FI_076]: 'Hammarland',
  [RegionalCoverage.LAU_FI_077]: 'Hankasalmi',
  [RegionalCoverage.LAU_FI_078]: 'Hanko',
  [RegionalCoverage.LAU_FI_079]: 'Harjavalta',
  [RegionalCoverage.LAU_FI_081]: 'Hartola',
  [RegionalCoverage.LAU_FI_082]: 'Hattula',
  [RegionalCoverage.LAU_FI_086]: 'Hausjärvi',
  [RegionalCoverage.LAU_FI_111]: 'Heinola',
  [RegionalCoverage.LAU_FI_090]: 'Heinävesi',
  [RegionalCoverage.LAU_FI_091]: 'Helsinki',
  [RegionalCoverage.LAU_FI_097]: 'Hirvensalmi',
  [RegionalCoverage.LAU_FI_098]: 'Hollola',
  [RegionalCoverage.LAU_FI_099]: 'Honkajoki',
  [RegionalCoverage.LAU_FI_102]: 'Huittinen',
  [RegionalCoverage.LAU_FI_103]: 'Humppila',
  [RegionalCoverage.LAU_FI_105]: 'Hyrynsalmi',
  [RegionalCoverage.LAU_FI_106]: 'Hyvinkää',
  [RegionalCoverage.LAU_FI_108]: 'Hämeenkyrö',
  [RegionalCoverage.LAU_FI_109]: 'Hämeenlinna',
  [RegionalCoverage.LAU_FI_139]: 'Ii',
  [RegionalCoverage.LAU_FI_140]: 'Iisalmi',
  [RegionalCoverage.LAU_FI_142]: 'Iitti',
  [RegionalCoverage.LAU_FI_143]: 'Ikaalinen',
  [RegionalCoverage.LAU_FI_145]: 'Ilmajoki',
  [RegionalCoverage.LAU_FI_146]: 'Ilomantsi',
  [RegionalCoverage.LAU_FI_153]: 'Imatra',
  [RegionalCoverage.LAU_FI_148]: 'Inari',
  [RegionalCoverage.LAU_FI_149]: 'Inkoo',
  [RegionalCoverage.LAU_FI_151]: 'Isojoki',
  [RegionalCoverage.LAU_FI_152]: 'Isokyrö',
  [RegionalCoverage.LAU_FI_165]: 'Janakkala',
  [RegionalCoverage.LAU_FI_167]: 'Joensuu',
  [RegionalCoverage.LAU_FI_169]: 'Jokioinen',
  [RegionalCoverage.LAU_FI_170]: 'Jomala',
  [RegionalCoverage.LAU_FI_171]: 'Joroinen',
  [RegionalCoverage.LAU_FI_172]: 'Joutsa',
  [RegionalCoverage.LAU_FI_176]: 'Juuka',
  [RegionalCoverage.LAU_FI_177]: 'Juupajoki',
  [RegionalCoverage.LAU_FI_178]: 'Juva',
  [RegionalCoverage.LAU_FI_179]: 'Jyväskylä',
  [RegionalCoverage.LAU_FI_181]: 'Jämijärvi',
  [RegionalCoverage.LAU_FI_182]: 'Jämsä',
  [RegionalCoverage.LAU_FI_186]: 'Järvenpää',
  [RegionalCoverage.LAU_FI_202]: 'Kaarina',
  [RegionalCoverage.LAU_FI_204]: 'Kaavi',
  [RegionalCoverage.LAU_FI_205]: 'Kajaani',
  [RegionalCoverage.LAU_FI_208]: 'Kalajoki',
  [RegionalCoverage.LAU_FI_211]: 'Kangasala',
  [RegionalCoverage.LAU_FI_213]: 'Kangasniemi',
  [RegionalCoverage.LAU_FI_214]: 'Kankaanpää',
  [RegionalCoverage.LAU_FI_216]: 'Kannonkoski',
  [RegionalCoverage.LAU_FI_217]: 'Kannus',
  [RegionalCoverage.LAU_FI_218]: 'Karijoki',
  [RegionalCoverage.LAU_FI_224]: 'Karkkila',
  [RegionalCoverage.LAU_FI_226]: 'Karstula',
  [RegionalCoverage.LAU_FI_230]: 'Karvia',
  [RegionalCoverage.LAU_FI_231]: 'Kaskinen',
  [RegionalCoverage.LAU_FI_232]: 'Kauhajoki',
  [RegionalCoverage.LAU_FI_233]: 'Kauhava',
  [RegionalCoverage.LAU_FI_235]: 'Kauniainen',
  [RegionalCoverage.LAU_FI_236]: 'Kaustinen',
  [RegionalCoverage.LAU_FI_239]: 'Keitele',
  [RegionalCoverage.LAU_FI_240]: 'Kemi',
  [RegionalCoverage.LAU_FI_320]: 'Kemijärvi',
  [RegionalCoverage.LAU_FI_241]: 'Keminmaa',
  [RegionalCoverage.LAU_FI_322]: 'Kemiönsaari',
  [RegionalCoverage.LAU_FI_244]: 'Kempele',
  [RegionalCoverage.LAU_FI_245]: 'Kerava',
  [RegionalCoverage.LAU_FI_249]: 'Keuruu',
  [RegionalCoverage.LAU_FI_250]: 'Kihniö',
  [RegionalCoverage.LAU_FI_256]: 'Kinnula',
  [RegionalCoverage.LAU_FI_257]: 'Kirkkonummi',
  [RegionalCoverage.LAU_FI_260]: 'Kitee',
  [RegionalCoverage.LAU_FI_261]: 'Kittilä',
  [RegionalCoverage.LAU_FI_263]: 'Kiuruvesi',
  [RegionalCoverage.LAU_FI_265]: 'Kivijärvi',
  [RegionalCoverage.LAU_FI_271]: 'Kokemäki',
  [RegionalCoverage.LAU_FI_272]: 'Kokkola',
  [RegionalCoverage.LAU_FI_273]: 'Kolari',
  [RegionalCoverage.LAU_FI_275]: 'Konnevesi',
  [RegionalCoverage.LAU_FI_276]: 'Kontiolahti',
  [RegionalCoverage.LAU_FI_280]: 'Korsnäs',
  [RegionalCoverage.LAU_FI_284]: 'Koski Tl',
  [RegionalCoverage.LAU_FI_285]: 'Kotka',
  [RegionalCoverage.LAU_FI_286]: 'Kouvola',
  [RegionalCoverage.LAU_FI_287]: 'Kristiinankaupunki',
  [RegionalCoverage.LAU_FI_288]: 'Kruunupyy',
  [RegionalCoverage.LAU_FI_290]: 'Kuhmo',
  [RegionalCoverage.LAU_FI_291]: 'Kuhmoinen',
  [RegionalCoverage.LAU_FI_295]: 'Kumlinge',
  [RegionalCoverage.LAU_FI_297]: 'Kuopio',
  [RegionalCoverage.LAU_FI_300]: 'Kuortane',
  [RegionalCoverage.LAU_FI_301]: 'Kurikka',
  [RegionalCoverage.LAU_FI_304]: 'Kustavi',
  [RegionalCoverage.LAU_FI_305]: 'Kuusamo',
  [RegionalCoverage.LAU_FI_312]: 'Kyyjärvi',
  [RegionalCoverage.LAU_FI_316]: 'Kärkölä',
  [RegionalCoverage.LAU_FI_317]: 'Kärsämäki',
  [RegionalCoverage.LAU_FI_318]: 'Kökar',
  [RegionalCoverage.LAU_FI_398]: 'Lahti',
  [RegionalCoverage.LAU_FI_399]: 'Laihia',
  [RegionalCoverage.LAU_FI_400]: 'Laitila',
  [RegionalCoverage.LAU_FI_407]: 'Lapinjärvi',
  [RegionalCoverage.LAU_FI_402]: 'Lapinlahti',
  [RegionalCoverage.LAU_FI_403]: 'Lappajärvi',
  [RegionalCoverage.LAU_FI_405]: 'Lappeenranta',
  [RegionalCoverage.LAU_FI_408]: 'Lapua',
  [RegionalCoverage.LAU_FI_410]: 'Laukaa',
  [RegionalCoverage.LAU_FI_416]: 'Lemi',
  [RegionalCoverage.LAU_FI_417]: 'Lemland',
  [RegionalCoverage.LAU_FI_418]: 'Lempäälä',
  [RegionalCoverage.LAU_FI_420]: 'Leppävirta',
  [RegionalCoverage.LAU_FI_421]: 'Lestijärvi',
  [RegionalCoverage.LAU_FI_422]: 'Lieksa',
  [RegionalCoverage.LAU_FI_423]: 'Lieto',
  [RegionalCoverage.LAU_FI_425]: 'Liminka',
  [RegionalCoverage.LAU_FI_426]: 'Liperi',
  [RegionalCoverage.LAU_FI_444]: 'Lohja',
  [RegionalCoverage.LAU_FI_430]: 'Loimaa',
  [RegionalCoverage.LAU_FI_433]: 'Loppi',
  [RegionalCoverage.LAU_FI_434]: 'Loviisa',
  [RegionalCoverage.LAU_FI_435]: 'Luhanka',
  [RegionalCoverage.LAU_FI_436]: 'Lumijoki',
  [RegionalCoverage.LAU_FI_438]: 'Lumparland',
  [RegionalCoverage.LAU_FI_440]: 'Luoto',
  [RegionalCoverage.LAU_FI_441]: 'Luumäki',
  [RegionalCoverage.LAU_FI_475]: 'Maalahti',
  [RegionalCoverage.LAU_FI_478]: 'Maarianhamina - Mariehamn',
  [RegionalCoverage.LAU_FI_480]: 'Marttila',
  [RegionalCoverage.LAU_FI_481]: 'Masku',
  [RegionalCoverage.LAU_FI_483]: 'Merijärvi',
  [RegionalCoverage.LAU_FI_484]: 'Merikarvia',
  [RegionalCoverage.LAU_FI_489]: 'Miehikkälä',
  [RegionalCoverage.LAU_FI_491]: 'Mikkeli',
  [RegionalCoverage.LAU_FI_494]: 'Muhos',
  [RegionalCoverage.LAU_FI_495]: 'Multia',
  [RegionalCoverage.LAU_FI_498]: 'Muonio',
  [RegionalCoverage.LAU_FI_499]: 'Mustasaari',
  [RegionalCoverage.LAU_FI_500]: 'Muurame',
  [RegionalCoverage.LAU_FI_503]: 'Mynämäki',
  [RegionalCoverage.LAU_FI_504]: 'Myrskylä',
  [RegionalCoverage.LAU_FI_505]: 'Mäntsälä',
  [RegionalCoverage.LAU_FI_508]: 'Mänttä-Vilppula',
  [RegionalCoverage.LAU_FI_507]: 'Mäntyharju',
  [RegionalCoverage.LAU_FI_529]: 'Naantali',
  [RegionalCoverage.LAU_FI_531]: 'Nakkila',
  [RegionalCoverage.LAU_FI_535]: 'Nivala',
  [RegionalCoverage.LAU_FI_536]: 'Nokia',
  [RegionalCoverage.LAU_FI_538]: 'Nousiainen',
  [RegionalCoverage.LAU_FI_541]: 'Nurmes',
  [RegionalCoverage.LAU_FI_543]: 'Nurmijärvi',
  [RegionalCoverage.LAU_FI_545]: 'Närpiö',
  [RegionalCoverage.LAU_FI_560]: 'Orimattila',
  [RegionalCoverage.LAU_FI_561]: 'Oripää',
  [RegionalCoverage.LAU_FI_562]: 'Orivesi',
  [RegionalCoverage.LAU_FI_563]: 'Oulainen',
  [RegionalCoverage.LAU_FI_564]: 'Oulu',
  [RegionalCoverage.LAU_FI_309]: 'Outokumpu',
  [RegionalCoverage.LAU_FI_576]: 'Padasjoki',
  [RegionalCoverage.LAU_FI_577]: 'Paimio',
  [RegionalCoverage.LAU_FI_578]: 'Paltamo',
  [RegionalCoverage.LAU_FI_445]: 'Parainen',
  [RegionalCoverage.LAU_FI_580]: 'Parikkala',
  [RegionalCoverage.LAU_FI_581]: 'Parkano',
  [RegionalCoverage.LAU_FI_599]: 'Pedersören kunta',
  [RegionalCoverage.LAU_FI_583]: 'Pelkosenniemi',
  [RegionalCoverage.LAU_FI_854]: 'Pello',
  [RegionalCoverage.LAU_FI_584]: 'Perho',
  [RegionalCoverage.LAU_FI_588]: 'Pertunmaa',
  [RegionalCoverage.LAU_FI_592]: 'Petäjävesi',
  [RegionalCoverage.LAU_FI_593]: 'Pieksämäki',
  [RegionalCoverage.LAU_FI_595]: 'Pielavesi',
  [RegionalCoverage.LAU_FI_598]: 'Pietarsaari',
  [RegionalCoverage.LAU_FI_601]: 'Pihtipudas',
  [RegionalCoverage.LAU_FI_604]: 'Pirkkala',
  [RegionalCoverage.LAU_FI_607]: 'Polvijärvi',
  [RegionalCoverage.LAU_FI_608]: 'Pomarkku',
  [RegionalCoverage.LAU_FI_609]: 'Pori',
  [RegionalCoverage.LAU_FI_611]: 'Pornainen',
  [RegionalCoverage.LAU_FI_638]: 'Porvoo',
  [RegionalCoverage.LAU_FI_614]: 'Posio',
  [RegionalCoverage.LAU_FI_615]: 'Pudasjärvi',
  [RegionalCoverage.LAU_FI_616]: 'Pukkila',
  [RegionalCoverage.LAU_FI_619]: 'Punkalaidun',
  [RegionalCoverage.LAU_FI_620]: 'Puolanka',
  [RegionalCoverage.LAU_FI_623]: 'Puumala',
  [RegionalCoverage.LAU_FI_624]: 'Pyhtää',
  [RegionalCoverage.LAU_FI_625]: 'Pyhäjoki',
  [RegionalCoverage.LAU_FI_626]: 'Pyhäjärvi',
  [RegionalCoverage.LAU_FI_630]: 'Pyhäntä',
  [RegionalCoverage.LAU_FI_631]: 'Pyhäranta',
  [RegionalCoverage.LAU_FI_635]: 'Pälkäne',
  [RegionalCoverage.LAU_FI_636]: 'Pöytyä',
  [RegionalCoverage.LAU_FI_678]: 'Raahe',
  [RegionalCoverage.LAU_FI_710]: 'Raasepori',
  [RegionalCoverage.LAU_FI_680]: 'Raisio',
  [RegionalCoverage.LAU_FI_681]: 'Rantasalmi',
  [RegionalCoverage.LAU_FI_683]: 'Ranua',
  [RegionalCoverage.LAU_FI_684]: 'Rauma',
  [RegionalCoverage.LAU_FI_686]: 'Rautalampi',
  [RegionalCoverage.LAU_FI_687]: 'Rautavaara',
  [RegionalCoverage.LAU_FI_689]: 'Rautjärvi',
  [RegionalCoverage.LAU_FI_691]: 'Reisjärvi',
  [RegionalCoverage.LAU_FI_694]: 'Riihimäki',
  [RegionalCoverage.LAU_FI_697]: 'Ristijärvi',
  [RegionalCoverage.LAU_FI_698]: 'Rovaniemi',
  [RegionalCoverage.LAU_FI_700]: 'Ruokolahti',
  [RegionalCoverage.LAU_FI_702]: 'Ruovesi',
  [RegionalCoverage.LAU_FI_704]: 'Rusko',
  [RegionalCoverage.LAU_FI_707]: 'Rääkkylä',
  [RegionalCoverage.LAU_FI_729]: 'Saarijärvi',
  [RegionalCoverage.LAU_FI_732]: 'Salla',
  [RegionalCoverage.LAU_FI_734]: 'Salo',
  [RegionalCoverage.LAU_FI_736]: 'Saltvik',
  [RegionalCoverage.LAU_FI_790]: 'Sastamala',
  [RegionalCoverage.LAU_FI_738]: 'Sauvo',
  [RegionalCoverage.LAU_FI_739]: 'Savitaipale',
  [RegionalCoverage.LAU_FI_740]: 'Savonlinna',
  [RegionalCoverage.LAU_FI_742]: 'Savukoski',
  [RegionalCoverage.LAU_FI_743]: 'Seinäjoki',
  [RegionalCoverage.LAU_FI_746]: 'Sievi',
  [RegionalCoverage.LAU_FI_747]: 'Siikainen',
  [RegionalCoverage.LAU_FI_748]: 'Siikajoki',
  [RegionalCoverage.LAU_FI_791]: 'Siikalatva',
  [RegionalCoverage.LAU_FI_749]: 'Siilinjärvi',
  [RegionalCoverage.LAU_FI_751]: 'Simo',
  [RegionalCoverage.LAU_FI_753]: 'Sipoo',
  [RegionalCoverage.LAU_FI_755]: 'Siuntio',
  [RegionalCoverage.LAU_FI_758]: 'Sodankylä',
  [RegionalCoverage.LAU_FI_759]: 'Soini',
  [RegionalCoverage.LAU_FI_761]: 'Somero',
  [RegionalCoverage.LAU_FI_762]: 'Sonkajärvi',
  [RegionalCoverage.LAU_FI_765]: 'Sotkamo',
  [RegionalCoverage.LAU_FI_766]: 'Sottunga',
  [RegionalCoverage.LAU_FI_768]: 'Sulkava',
  [RegionalCoverage.LAU_FI_771]: 'Sund',
  [RegionalCoverage.LAU_FI_777]: 'Suomussalmi',
  [RegionalCoverage.LAU_FI_778]: 'Suonenjoki',
  [RegionalCoverage.LAU_FI_781]: 'Sysmä',
  [RegionalCoverage.LAU_FI_783]: 'Säkylä',
  [RegionalCoverage.LAU_FI_831]: 'Taipalsaari',
  [RegionalCoverage.LAU_FI_832]: 'Taivalkoski',
  [RegionalCoverage.LAU_FI_833]: 'Taivassalo',
  [RegionalCoverage.LAU_FI_834]: 'Tammela',
  [RegionalCoverage.LAU_FI_837]: 'Tampere',
  [RegionalCoverage.LAU_FI_844]: 'Tervo',
  [RegionalCoverage.LAU_FI_845]: 'Tervola',
  [RegionalCoverage.LAU_FI_846]: 'Teuva',
  [RegionalCoverage.LAU_FI_848]: 'Tohmajärvi',
  [RegionalCoverage.LAU_FI_849]: 'Toholampi',
  [RegionalCoverage.LAU_FI_850]: 'Toivakka',
  [RegionalCoverage.LAU_FI_851]: 'Tornio',
  [RegionalCoverage.LAU_FI_853]: 'Turku',
  [RegionalCoverage.LAU_FI_857]: 'Tuusniemi',
  [RegionalCoverage.LAU_FI_858]: 'Tuusula',
  [RegionalCoverage.LAU_FI_859]: 'Tyrnävä',
  [RegionalCoverage.LAU_FI_886]: 'Ulvila',
  [RegionalCoverage.LAU_FI_887]: 'Urjala',
  [RegionalCoverage.LAU_FI_889]: 'Utajärvi',
  [RegionalCoverage.LAU_FI_890]: 'Utsjoki',
  [RegionalCoverage.LAU_FI_892]: 'Uurainen',
  [RegionalCoverage.LAU_FI_893]: 'Uusikaarlepyy',
  [RegionalCoverage.LAU_FI_895]: 'Uusikaupunki',
  [RegionalCoverage.LAU_FI_785]: 'Vaala',
  [RegionalCoverage.LAU_FI_905]: 'Vaasa',
  [RegionalCoverage.LAU_FI_908]: 'Valkeakoski',
  [RegionalCoverage.LAU_FI_092]: 'Vantaa',
  [RegionalCoverage.LAU_FI_915]: 'Varkaus',
  [RegionalCoverage.LAU_FI_918]: 'Vehmaa',
  [RegionalCoverage.LAU_FI_921]: 'Vesanto',
  [RegionalCoverage.LAU_FI_922]: 'Vesilahti',
  [RegionalCoverage.LAU_FI_924]: 'Veteli',
  [RegionalCoverage.LAU_FI_925]: 'Vieremä',
  [RegionalCoverage.LAU_FI_927]: 'Vihti',
  [RegionalCoverage.LAU_FI_931]: 'Viitasaari',
  [RegionalCoverage.LAU_FI_934]: 'Vimpeli',
  [RegionalCoverage.LAU_FI_935]: 'Virolahti',
  [RegionalCoverage.LAU_FI_936]: 'Virrat',
  [RegionalCoverage.LAU_FI_941]: 'Vårdö',
  [RegionalCoverage.LAU_FI_946]: 'Vöyri',
  [RegionalCoverage.LAU_FI_976]: 'Ylitornio',
  [RegionalCoverage.LAU_FI_977]: 'Ylivieska',
  [RegionalCoverage.LAU_FI_980]: 'Ylöjärvi',
  [RegionalCoverage.LAU_FI_981]: 'Ypäjä',
  [RegionalCoverage.LAU_FI_989]: 'Ähtäri',
  [RegionalCoverage.LAU_FI_992]: 'Äänekoski',
};

export function labelToRegionalCoverage(label: string): RegionalCoverage {
  const regionalCoverage = getObjectKeyByValue(regionalCoverageLabels, label) as RegionalCoverage | undefined;
  if (regionalCoverage) {
    return regionalCoverage;
  } else {
    throw new Error(`Unknown regionalCoverage label: ${label}`);
  }
}