export enum TransportMode {
  AIR = 'https://w3id.org/mobilitydcat-ap/transport-mode/air',
  BICYCLE = 'https://w3id.org/mobilitydcat-ap/transport-mode/bicycle',
  BIKE_HIRE = 'https://w3id.org/mobilitydcat-ap/transport-mode/bike-hire',
  BIKE_SHARING = 'https://w3id.org/mobilitydcat-ap/transport-mode/bike-sharing',
  BUS = 'https://w3id.org/mobilitydcat-ap/transport-mode/bus',
  CAR = 'https://w3id.org/mobilitydcat-ap/transport-mode/car',
  CAR_HIRE = 'https://w3id.org/mobilitydcat-ap/transport-mode/car-hire',
  CAR_POOLING = 'https://w3id.org/mobilitydcat-ap/transport-mode/car-pooling',
  CAR_SHARING = 'https://w3id.org/mobilitydcat-ap/transport-mode/car-sharing',
  E_SCOOTER = 'https://w3id.org/mobilitydcat-ap/transport-mode/e-scooter',
  LONG_DISTANCE_COACH = 'https://w3id.org/mobilitydcat-ap/transport-mode/long-distance-coach',
  LONG_DISTANCE_RAIL = 'https://w3id.org/mobilitydcat-ap/transport-mode/long-distance-rail',
  MARITIME = 'https://w3id.org/mobilitydcat-ap/transport-mode/maritime',
  METRO_SUBWAY_TRAIN = 'https://w3id.org/mobilitydcat-ap/transport-mode/metro-subway-train',
  MOTORCYCLE = 'https://w3id.org/mobilitydcat-ap/transport-mode/motorcycle',
  OTHER = 'https://w3id.org/mobilitydcat-ap/transport-mode/other',
  PEDESTRIAN = 'https://w3id.org/mobilitydcat-ap/transport-mode/pedestrian',
  REGIONAL_AND_LOCAL_RAIL = 'https://w3id.org/mobilitydcat-ap/transport-mode/regional-and-local-rail',
  RIDE_POOLING = 'https://w3id.org/mobilitydcat-ap/transport-mode/ride-pooling',
  SHUTTLE_BUS = 'https://w3id.org/mobilitydcat-ap/transport-mode/shuttle-bus',
  SHUTTLE_FERRY = 'https://w3id.org/mobilitydcat-ap/transport-mode/shuttle-ferry',
  TAXI = 'https://w3id.org/mobilitydcat-ap/transport-mode/taxi',
  TRAM_LIGHT_RAIL = 'https://w3id.org/mobilitydcat-ap/transport-mode/tram-light-rail',
  TRUCK = 'https://w3id.org/mobilitydcat-ap/transport-mode/truck',
}